;
; File generated by cc65 v 2.19 - Git 547d923
;
	.fopt		compiler,"cc65 v 2.19 - Git 547d923"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "C:\Users\Alex\Chased3D\chased3d.c", 20937, 1788473348
	.dbg		file, "C:\tools\cc65\include/atari.h", 22152, 1786840064
	.dbg		file, "C:\tools\cc65\include/_atarios.h", 40084, 1786840064
	.dbg		file, "C:\tools\cc65\include/_gtia.h", 13839, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pbi.h", 3143, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pokey.h", 11376, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pia.h", 3044, 1786840064
	.dbg		file, "C:\tools\cc65\include/_antic.h", 11827, 1786840064
	.dbg		file, "C:\tools\cc65\include/stdlib.h", 6948, 1786840065
	.dbg		file, "C:\Users\Alex\Chased3D/maze.h", 550, 1787868964
	.dbg		file, "C:\Users\Alex\Chased3D/trig3d.h", 333, 1787781160
	.dbg		file, "C:\Users\Alex\Chased3D/view3d.h", 1410, 1788473348
	.dbg		file, "C:\Users\Alex\Chased3D/sprite3d.h", 910, 1787954059
	.dbg		file, "C:\Users\Alex\Chased3D/melody.h", 326, 1787954059
	.dbg		file, "C:\Users\Alex\Chased3D/textplot.h", 440, 1788473040
	.dbg		file, "C:\Users\Alex\Chased3D/splash_screen.h", 127, 1788301734
	.forceimport	__STARTUP__
	.dbg		sym, "maze_map", "00", extern, "_maze_map"
	.dbg		sym, "sin3d", "00", extern, "_sin3d"
	.dbg		sym, "startup_portb", "00", extern, "_startup_portb"
	.dbg		sym, "startup_memtop", "00", extern, "_startup_memtop"
	.import		_waitvsync
	.import		_get_tv
	.import		_rand
	.import		_srand
	.import		_abs
	.import		_maze_map
	.import		_maze_load_level
	.import		_maze_solid
	.import		_maze_set_exit_open
	.import		_sin3d
	.import		_view3d_init
	.import		_view3d_render
	.import		_view3d_floor_motion
	.import		_minimap_build
	.import		_minimap_show
	.import		_minimap_update
	.import		_hud_set_fps
	.import		_hud_set_targets
	.import		_hud_set_game
	.import		_hud_set_decoy
	.import		_sprite3d_init
	.import		_sprite3d_build_targets
	.import		_sprite3d_build_laser
	.import		_sprite3d_locate_exit
	.import		_sprite3d_draw_targets
	.import		_sprite3d_draw_pursuer
	.import		_sprite3d_draw_decoy
	.import		_sprite3d_collect
	.import		_sprite3d_hit_laser
	.import		_sprite3d_targets_left
	.import		_sprite3d_clear_all
	.import		_sprite3d_reached_exit
	.import		_melody_install
	.import		_melody_play
	.import		_melody_pickup
	.import		_melody_playing
	.import		_melody_threat_play
	.import		_melody_set_threat_level
	.import		_melody_laser_buzz
	.import		_textplot_print_fullscreen
	.import		_splash_screen_show
	.import		_splash_screen_rainbow
	.import		_startup_portb
	.import		_startup_memtop
	.export		_main

.segment	"DATA"

_frame_ticks:
	.byte	$01
_lives:
	.byte	$03
_level:
	.byte	$01
_decoy_available:
	.byte	$01
_decoy_recharge_ticks:
	.byte	$C8
_pursuer_dir_x:
	.byte	$00
_pursuer_dir_y:
	.byte	$00
_pursuer_retarget_timer:
	.byte	$33

.segment	"RODATA"

S000B:
	.byte	$43,$31,$32,$43,$31,$34,$45,$31,$38,$42,$30,$38,$43,$31,$34,$41
	.byte	$31,$34,$47,$31,$38,$46,$31,$34,$45,$31,$38,$44,$31,$38,$45,$31
	.byte	$34,$44,$31,$34,$43,$31,$34,$50,$30,$31,$00
S0009:
	.byte	$43,$31,$34,$43,$31,$34,$43,$31,$34,$43,$32,$34,$43,$32,$34,$43
	.byte	$32,$34,$42,$31,$38,$41,$31,$38,$47,$31,$38,$46,$31,$38,$45,$31
	.byte	$38,$44,$31,$38,$43,$31,$32,$00
S000C:
	.byte	$43,$31,$34,$43,$31,$34,$45,$31,$34,$43,$31,$38,$46,$31,$38,$43
	.byte	$31,$38,$45,$31,$38,$43,$31,$34,$44,$31,$34,$50,$30,$34,$00
S000F	:=	S000C+0
S0007	:=	S000C+0
S0005:
	.byte	$50,$72,$65,$73,$73,$20,$53,$70,$61,$63,$65,$20,$6F,$72,$20,$46
	.byte	$69,$72,$65,$00
S000A:
	.byte	$41,$31,$34,$43,$32,$38,$42,$31,$38,$41,$31,$34,$47,$31,$34,$41
	.byte	$31,$31,$00
S000D:
	.byte	$41,$30,$32,$41,$30,$32,$45,$31,$32,$41,$30,$32,$41,$30,$32,$45
	.byte	$31,$32,$00
S0001:
	.byte	$43,$32,$31,$45,$32,$31,$47,$32,$31,$45,$32,$31,$43,$32,$32,$00
S0008:
	.byte	$59,$4F,$55,$20,$44,$49,$44,$20,$49,$54,$20,$21,$21,$21,$00
S0004:
	.byte	$43,$32,$31,$45,$32,$31,$47,$32,$31,$43,$32,$32,$00
S0003:
	.byte	$43,$32,$31,$47,$32,$31,$43,$32,$32,$00
S0002:
	.byte	$47,$31,$31,$44,$31,$31,$47,$30,$32,$00
S0006:
	.byte	$47,$61,$6D,$65,$20,$4F,$76,$65,$72,$00
S000E:
	.byte	$44,$45,$43,$4F,$59,$00

.segment	"BSS"

_score:
	.res	2,$00
_high_score:
	.res	2,$00
_player_x:
	.res	2,$00
_player_y:
	.res	2,$00
_player_angle:
	.res	2,$00
_pursuer_x:
	.res	2,$00
_pursuer_y:
	.res	2,$00
_decoy_x:
	.res	2,$00
_decoy_y:
	.res	2,$00
_decoy_active:
	.res	1,$00
_decoy_capture_ticks:
	.res	1,$00
_decoy_active_ticks:
	.res	2,$00
_laser_elapsed_ticks:
	.res	2,$00
_laser_period_ticks:
	.res	2,$00
_floor_motion_units:
	.res	2,$00
_threat_old_color:
	.res	1,$00
_threat_color_active:
	.res	1,$00
_pursuer_target_col:
	.res	1,$00
_pursuer_target_row:
	.res	1,$00
_pursuer_stuck_col:
	.res	1,$00
_pursuer_stuck_row:
	.res	1,$00
_pursuer_stuck_ticks:
	.res	2,$00

; ---------------------------------------------------------------
; unsigned char __near__ read_key (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_key: near

	.dbg	func, "read_key", "00", static, "_read_key"

.segment	"CODE"

;
; if ((*(volatile unsigned char *)KBD_SKSTAT & 0x04) != 0) return 0xFF;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 87
	lda     $D20F
	and     #$04
	beq     L0004
	ldx     #$00
	lda     #$FF
	rts
;
; return *(volatile unsigned char *)KBD_KBCODE & 0x3F;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 88
L0004:	lda     $D209
	and     #$3F
	ldx     #$00
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 89
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ wait_frame (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_wait_frame: near

	.dbg	func, "wait_frame", "00", static, "_wait_frame"

.segment	"CODE"

;
; *(volatile unsigned char *)OS_ATTRACT = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 93
	lda     #$00
	sta     $004D
;
; waitvsync();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 94
	jmp     _waitvsync

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ try_move (int delta_x, int delta_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_try_move: near

	.dbg	func, "try_move", "00", static, "_try_move"
	.dbg	sym, "delta_x", "00", auto, 2
	.dbg	sym, "delta_y", "00", auto, 0
	.dbg	sym, "next_x", "00", auto, -2
	.dbg	sym, "next_y", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 98
	jsr     pushax
;
; next_x = (unsigned int)((int)player_x + delta_x);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 102
	jsr     decsp4
	ldy     #$07
	jsr     ldaxysp
	clc
	adc     _player_x
	pha
	txa
	adc     _player_x+1
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; next_y = (unsigned int)((int)player_y + delta_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 103
	ldy     #$05
	jsr     ldaxysp
	clc
	adc     _player_y
	pha
	txa
	adc     _player_y+1
	tax
	pla
	jsr     stax0sp
;
; if (!maze_solid((unsigned char)(next_x >> 8), (unsigned char)(player_y >> 8)))
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 105
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	lda     _player_y+1
	jsr     _maze_solid
	tax
	bne     L0002
;
; player_x = next_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 106
	ldy     #$03
	jsr     ldaxysp
	sta     _player_x
	stx     _player_x+1
;
; if (!maze_solid((unsigned char)(player_x >> 8), (unsigned char)(next_y >> 8)))
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 107
L0002:	lda     _player_x+1
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0003
;
; player_y = next_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 108
	jsr     ldax0sp
	sta     _player_y
	stx     _player_y+1
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 109
L0003:	jmp     incsp8

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ step_forward (signed char direction)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_step_forward: near

	.dbg	func, "step_forward", "00", static, "_step_forward"
	.dbg	sym, "direction", "00", auto, 0
	.dbg	sym, "idx", "00", auto, -1
	.dbg	sym, "dir_x", "00", auto, -3
	.dbg	sym, "dir_y", "00", auto, -5
	.dbg	sym, "step", "00", auto, -7
	.dbg	sym, "moved_x", "00", auto, -9
	.dbg	sym, "moved_y", "00", auto, -11
	.dbg	sym, "moved", "00", auto, -13
	.dbg	sym, "old_x", "00", auto, -15
	.dbg	sym, "old_y", "00", auto, -17

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 112
	jsr     pusha
;
; step = (int)MOVE_PER_TICK * (int)frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 123
	ldy     #$11
	jsr     subysp
	lda     _frame_ticks
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	ldy     #$0A
	jsr     staxysp
;
; idx = (unsigned char)(player_angle >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 124
	lda     _player_angle+1
	ldy     #$10
	sta     (c_sp),y
;
; dir_x = sin3d[(unsigned char)(idx + 64)];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 125
	ldx     #$00
	lda     (c_sp),y
	ldy     #$40
	jsr     incaxy
	ldx     #$00
	asl     a
	bcc     L0018
	inx
	clc
L0018:	adc     #<(_sin3d)
	tay
	txa
	adc     #>(_sin3d)
	tax
	tya
	jsr     ldaxi
	ldy     #$0E
	jsr     staxysp
;
; dir_y = sin3d[idx];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 126
	ldy     #$10
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0019
	inx
	clc
L0019:	adc     #<(_sin3d)
	tay
	txa
	adc     #>(_sin3d)
	tax
	tya
	jsr     ldaxi
	ldy     #$0C
	jsr     staxysp
;
; if (direction < 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 127
	ldy     #$11
	lda     (c_sp),y
	asl     a
	bcc     L0002
;
; dir_x = -dir_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 128
	ldy     #$0F
	jsr     ldaxysp
	jsr     negax
	ldy     #$0E
	jsr     staxysp
;
; dir_y = -dir_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 129
	ldy     #$0D
	jsr     ldaxysp
	jsr     negax
	ldy     #$0C
	jsr     staxysp
;
; old_x = player_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 131
L0002:	lda     _player_x
	ldx     _player_x+1
	ldy     #$02
	jsr     staxysp
;
; old_y = player_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 132
	lda     _player_y
	ldx     _player_y+1
	jsr     stax0sp
;
; try_move((dir_x * step) >> 8, (dir_y * step) >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 133
	ldy     #$11
	jsr     pushwysp
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosmulax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0004
	dex
L0004:	jsr     pushax
	ldy     #$11
	jsr     pushwysp
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosmulax
	txa
	cpx     #$80
	ldx     #$00
	bcc     L0005
	dex
L0005:	jsr     _try_move
;
; moved_x = abs((int)player_x - (int)old_x);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 134
	lda     _player_x
	sec
	ldy     #$02
	sbc     (c_sp),y
	pha
	lda     _player_x+1
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     _abs
	ldy     #$08
	jsr     staxysp
;
; moved_y = abs((int)player_y - (int)old_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 135
	lda     _player_y
	sec
	ldy     #$00
	sbc     (c_sp),y
	pha
	lda     _player_y+1
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     _abs
	ldy     #$06
	jsr     staxysp
;
; moved = moved_x > moved_y
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 136
	ldy     #$0B
	jsr     pushwysp
;
; ? moved_x + (moved_y >> 1) : moved_y + (moved_x >> 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 137
	ldy     #$09
	jsr     ldaxysp
	jsr     tosicmp
	bmi     L0006
	beq     L0006
	ldy     #$07
	jsr     ldaxysp
	jsr     asrax1
	clc
	ldy     #$08
	jmp     L0021
L0006:	ldy     #$09
	jsr     ldaxysp
	jsr     asrax1
	clc
	ldy     #$06
L0021:	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	ldy     #$04
	jsr     staxysp
;
; floor_motion_units += direction > 0 ? moved : -moved;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 138
	ldy     #$11
	lda     (c_sp),y
	sec
	sbc     #$01
	bvs     L0009
	eor     #$80
L0009:	bpl     L000A
	ldy     #$05
	jsr     ldaxysp
	jmp     L000B
L000A:	ldy     #$05
	jsr     ldaxysp
	jsr     negax
L000B:	clc
	adc     _floor_motion_units
	sta     _floor_motion_units
	txa
	adc     _floor_motion_units+1
;
; while (floor_motion_units >= FLOOR_SCROLL_DISTANCE) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 139
	jmp     L001C
;
; view3d_floor_motion(1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 140
L001A:	lda     #$01
	jsr     _view3d_floor_motion
;
; floor_motion_units -= FLOOR_SCROLL_DISTANCE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 141
	lda     _floor_motion_units
	sec
	sta     _floor_motion_units
	lda     _floor_motion_units+1
	sbc     #$01
L001C:	sta     _floor_motion_units+1
;
; while (floor_motion_units >= FLOOR_SCROLL_DISTANCE) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 139
	lda     _floor_motion_units
	cmp     #$00
	lda     _floor_motion_units+1
	sbc     #$01
	bvs     L000F
	eor     #$80
L000F:	bmi     L001A
;
; while (floor_motion_units <= -FLOOR_SCROLL_DISTANCE) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 143
	jmp     L0012
;
; view3d_floor_motion(-1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 144
L0010:	lda     #$FF
	jsr     _view3d_floor_motion
;
; floor_motion_units += FLOOR_SCROLL_DISTANCE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 145
	clc
	lda     #$01
	adc     _floor_motion_units+1
	sta     _floor_motion_units+1
;
; while (floor_motion_units <= -FLOOR_SCROLL_DISTANCE) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 143
L0012:	lda     _floor_motion_units
	cmp     #$01
	lda     _floor_motion_units+1
	sbc     #$FF
	bvc     L0013
	eor     #$80
L0013:	bmi     L0010
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 147
	ldy     #$12
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ place_pursuer_at_start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_place_pursuer_at_start: near

	.dbg	func, "place_pursuer_at_start", "00", static, "_place_pursuer_at_start"
	.dbg	sym, "col", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2

.segment	"CODE"

;
; for (row = MAZE_H - 2; row > 0; --row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 167
	jsr     decsp2
	lda     #$39
	ldy     #$00
L000C:	sta     (c_sp),y
	lda     (c_sp),y
	beq     L0003
;
; for (col = MAZE_W - 2; col > 0; --col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 168
	lda     #$12
	iny
L000B:	sta     (c_sp),y
	lda     (c_sp),y
	beq     L0004
;
; if (maze_map[row][col] != 0) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 169
	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	bne     L0008
;
; pursuer_x = ((unsigned int)col << 8) | 0x80u;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 170
	ldy     #$01
	lda     (c_sp),y
	sta     _pursuer_x+1
	lda     #$80
	sta     _pursuer_x
;
; pursuer_y = ((unsigned int)row << 8) | 0x80u;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 171
	dey
	lda     (c_sp),y
	sta     _pursuer_y+1
	lda     #$80
	sta     _pursuer_y
;
; pursuer_stuck_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 172
	iny
	lda     (c_sp),y
	sta     _pursuer_stuck_col
;
; pursuer_stuck_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 173
	dey
	lda     (c_sp),y
	sta     _pursuer_stuck_row
;
; pursuer_stuck_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 174
	tya
	sta     _pursuer_stuck_ticks
	sta     _pursuer_stuck_ticks+1
;
; return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 175
	jmp     incsp2
;
; for (col = MAZE_W - 2; col > 0; --col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 168
L0008:	ldy     #$01
	lda     (c_sp),y
	sec
	sbc     #$01
	jmp     L000B
;
; for (row = MAZE_H - 2; row > 0; --row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 167
L0004:	dey
	lda     (c_sp),y
	sec
	sbc     #$01
	jmp     L000C
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 178
L0003:	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ respawn_pursuer (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_respawn_pursuer: near

	.dbg	func, "respawn_pursuer", "00", static, "_respawn_pursuer"
	.dbg	sym, "col", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2
	.dbg	sym, "chosen_col", "00", auto, -3
	.dbg	sym, "chosen_row", "00", auto, -4
	.dbg	sym, "player_col", "00", auto, -5
	.dbg	sym, "player_row", "00", auto, -6
	.dbg	sym, "current_col", "00", auto, -7
	.dbg	sym, "current_row", "00", auto, -8
	.dbg	sym, "choices", "00", auto, -10

.segment	"CODE"

;
; player_col = (unsigned char)(player_x >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 192
	ldy     #$0A
	jsr     subysp
	lda     _player_x+1
	ldy     #$05
	sta     (c_sp),y
;
; player_row = (unsigned char)(player_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 193
	lda     _player_y+1
	dey
	sta     (c_sp),y
;
; current_col = (unsigned char)(pursuer_x >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 194
	lda     _pursuer_x+1
	dey
	sta     (c_sp),y
;
; current_row = (unsigned char)(pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 195
	lda     _pursuer_y+1
	dey
	sta     (c_sp),y
;
; choices = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 196
	ldx     #$00
	txa
	jsr     stax0sp
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 197
	ldy     #$08
L001C:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0003
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 198
	lda     #$00
	iny
L001B:	sta     (c_sp),y
	cmp     #$14
	jcs     L0004
;
; if (maze_solid(col, row)) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 199
	lda     (c_sp),y
	jsr     pusha
	ldy     #$09
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0008
;
; if (col == player_col && row == player_row) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 200
	ldy     #$09
	lda     (c_sp),y
	ldy     #$05
	cmp     (c_sp),y
	bne     L000B
	ldy     #$08
	lda     (c_sp),y
	ldy     #$04
	cmp     (c_sp),y
	beq     L0008
;
; if (col == current_col && row == current_row) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 201
L000B:	ldy     #$09
	lda     (c_sp),y
	ldy     #$03
	cmp     (c_sp),y
	bne     L000F
	ldy     #$08
	lda     (c_sp),y
	ldy     #$02
	cmp     (c_sp),y
	beq     L0008
;
; && col == (unsigned char)(decoy_x >> 8)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 203
L000F:	lda     _decoy_active
	beq     L0013
	lda     _decoy_x+1
;
; && row == (unsigned char)(decoy_y >> 8)) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 204
	ldy     #$09
	cmp     (c_sp),y
	bne     L0013
	lda     _decoy_y+1
	dey
	cmp     (c_sp),y
	beq     L0008
;
; ++choices;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 205
L0013:	lda     #$01
	jsr     addeq0sp
;
; if ((unsigned int)rand() % choices != 0) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 206
	jsr     _rand
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosumodax
	cpx     #$00
	bne     L0008
	cmp     #$00
	bne     L0008
;
; chosen_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 207
	ldy     #$09
	lda     (c_sp),y
	ldy     #$07
	sta     (c_sp),y
;
; chosen_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 208
	iny
	lda     (c_sp),y
	ldy     #$06
	sta     (c_sp),y
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 198
L0008:	ldy     #$09
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001B
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 197
L0004:	dey
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001C
;
; if (choices == 0) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 211
L0003:	ldy     #$00
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	beq     L0001
;
; pursuer_x = ((unsigned int)chosen_col << 8) | 0x80u;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 213
	ldy     #$07
	lda     (c_sp),y
	sta     _pursuer_x+1
	lda     #$80
	sta     _pursuer_x
;
; pursuer_y = ((unsigned int)chosen_row << 8) | 0x80u;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 214
	dey
	lda     (c_sp),y
	sta     _pursuer_y+1
	lda     #$80
	sta     _pursuer_y
;
; pursuer_dir_x = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 215
	lda     #$00
	sta     _pursuer_dir_x
;
; pursuer_dir_y = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 216
	sta     _pursuer_dir_y
;
; pursuer_retarget_timer = RETARGET_STALE_TICKS + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 217
	lda     #$33
	sta     _pursuer_retarget_timer
;
; pursuer_stuck_col = chosen_col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 218
	iny
	lda     (c_sp),y
	sta     _pursuer_stuck_col
;
; pursuer_stuck_row = chosen_row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 219
	dey
	lda     (c_sp),y
	sta     _pursuer_stuck_row
;
; pursuer_stuck_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 220
	lda     #$00
	sta     _pursuer_stuck_ticks
	sta     _pursuer_stuck_ticks+1
;
; melody_play(PURSUER_RESPAWN_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 221
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _melody_play
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 222
L0001:	ldy     #$0A
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ move_pursuer (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_pursuer: near

	.dbg	func, "move_pursuer", "00", static, "_move_pursuer"
	.dbg	sym, "col", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2
	.dbg	sym, "next_col", "00", auto, -3
	.dbg	sym, "next_row", "00", auto, -4
	.dbg	sym, "need_retarget", "00", auto, -5
	.dbg	sym, "i", "00", auto, -6
	.dbg	sym, "best", "00", auto, -7
	.dbg	sym, "best_distance", "00", auto, -9
	.dbg	sym, "distance", "00", auto, -11
	.dbg	sym, "candidate_x", "00", auto, -13
	.dbg	sym, "candidate_y", "00", auto, -15

.segment	"CODE"

;
; col = (unsigned char)(pursuer_x >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 243
	ldy     #$0F
	jsr     subysp
	lda     _pursuer_x+1
	ldy     #$0E
	sta     (c_sp),y
;
; row = (unsigned char)(pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 244
	lda     _pursuer_y+1
	dey
	sta     (c_sp),y
;
; && col == (unsigned char)(decoy_x >> 8)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 247
	lda     _decoy_active
	beq     L0042
	lda     _decoy_x+1
;
; && row == (unsigned char)(decoy_y >> 8)) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 248
	iny
	cmp     (c_sp),y
	bne     L0042
	lda     _decoy_y+1
	dey
	cmp     (c_sp),y
	bne     L0042
;
; if (decoy_capture_ticks == 0) melody_play(DECOY_TRAPPED_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 249
	lda     _decoy_capture_ticks
	bne     L0040
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _melody_play
;
; decoy_capture_ticks += frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 250
L0040:	lda     _frame_ticks
	clc
	adc     _decoy_capture_ticks
	sta     _decoy_capture_ticks
;
; if (decoy_capture_ticks < DECOY_CAPTURE_TICKS) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 251
	cmp     #$28
	bcs     L0041
;
; pursuer_stuck_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 252
	ldy     #$0E
	lda     (c_sp),y
	sta     _pursuer_stuck_col
;
; pursuer_stuck_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 253
	dey
	lda     (c_sp),y
	sta     _pursuer_stuck_row
;
; pursuer_stuck_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 254
	lda     #$00
	sta     _pursuer_stuck_ticks
	sta     _pursuer_stuck_ticks+1
;
; return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 255
	jmp     L0034
;
; decoy_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 257
L0041:	lda     #$00
	sta     _decoy_active
;
; decoy_available = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 258
	sta     _decoy_available
;
; decoy_capture_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 259
	sta     _decoy_capture_ticks
;
; decoy_recharge_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 260
	sta     _decoy_recharge_ticks
;
; pursuer_retarget_timer = RETARGET_STALE_TICKS + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 261
	lda     #$33
	sta     _pursuer_retarget_timer
;
; pursuer_retarget_timer += frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 264
L0042:	lda     _frame_ticks
	clc
	adc     _pursuer_retarget_timer
	sta     _pursuer_retarget_timer
;
; need_retarget = pursuer_retarget_timer > RETARGET_STALE_TICKS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 265
	cmp     #$33
	lda     #$00
	rol     a
	ldy     #$0A
	sta     (c_sp),y
;
; if (col == pursuer_target_col && row == pursuer_target_row) need_retarget = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 266
	ldy     #$0E
	lda     (c_sp),y
	cmp     _pursuer_target_col
	bne     L0008
	dey
	lda     (c_sp),y
	cmp     _pursuer_target_row
	bne     L0008
	lda     #$01
	ldy     #$0A
	sta     (c_sp),y
;
; if (!need_retarget && (pursuer_dir_x != 0 || pursuer_dir_y != 0)) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 267
L0008:	ldy     #$0A
	lda     (c_sp),y
	bne     L0049
	lda     _pursuer_dir_x
	bne     L0048
	lda     _pursuer_dir_y
	beq     L0049
;
; next_col = (unsigned char)(col + pursuer_dir_x);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 268
L0048:	lda     _pursuer_dir_x
	clc
	ldy     #$0E
	adc     (c_sp),y
	ldy     #$0C
	sta     (c_sp),y
;
; next_row = (unsigned char)(row + pursuer_dir_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 269
	lda     _pursuer_dir_y
	clc
	iny
	adc     (c_sp),y
	ldy     #$0B
	sta     (c_sp),y
;
; if (maze_solid(next_col, row) || maze_solid(col, next_row)) need_retarget = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 270
	iny
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0E
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0017
	ldy     #$0E
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0C
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	beq     L0016
L0017:	lda     #$01
	ldy     #$0A
	sta     (c_sp),y
;
; if (need_retarget) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 273
L0016:	ldy     #$0A
L0049:	lda     (c_sp),y
	jeq     L0019
;
; (decoy_active ? decoy_x : player_x) >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 275
	lda     _decoy_active
	beq     L001A
	ldx     _decoy_x+1
	jmp     L001B
L001A:	ldx     _player_x+1
L001B:	stx     _pursuer_target_col
;
; (decoy_active ? decoy_y : player_y) >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 277
	lda     _decoy_active
	beq     L001C
	ldx     _decoy_y+1
	jmp     L001D
L001C:	ldx     _player_y+1
L001D:	stx     _pursuer_target_row
;
; pursuer_retarget_timer = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 278
	lda     #$00
	sta     _pursuer_retarget_timer
;
; best = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 280
	ldy     #$08
	sta     (c_sp),y
;
; best_distance = 32767;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 281
	ldx     #$7F
	lda     #$FF
	ldy     #$06
	jsr     staxysp
;
; for (i = 0; i < 8; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 282
	lda     #$00
	ldy     #$09
L003C:	sta     (c_sp),y
	cmp     #$08
	jcs     L001F
;
; next_col = (unsigned char)(col + dir_x[i]);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 283
	lda     #<(M0001)
	ldx     #>(M0001)
	clc
	adc     (c_sp),y
	bcc     L0022
	inx
L0022:	ldy     #$00
	jsr     ldaidx
	clc
	ldy     #$0E
	adc     (c_sp),y
	ldy     #$0C
	sta     (c_sp),y
;
; next_row = (unsigned char)(row + dir_y[i]);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 284
	lda     #<(M0002)
	ldx     #>(M0002)
	clc
	ldy     #$09
	adc     (c_sp),y
	bcc     L0023
	inx
L0023:	ldy     #$00
	jsr     ldaidx
	clc
	ldy     #$0D
	adc     (c_sp),y
	ldy     #$0B
	sta     (c_sp),y
;
; if (maze_solid(next_col, row) || maze_solid(col, next_row)) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 285
	iny
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0E
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0020
	ldy     #$0E
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0C
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0020
;
; distance = abs((int)next_col - (int)pursuer_target_col)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 286
	ldy     #$0C
	lda     (c_sp),y
	sec
	sbc     _pursuer_target_col
	bcs     L0035
	dex
;
; + abs((int)next_row - (int)pursuer_target_row);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 287
L0035:	jsr     _abs
	jsr     pushax
	ldy     #$0D
	lda     (c_sp),y
	sec
	sbc     _pursuer_target_row
	ldx     #$00
	bcs     L0036
	dex
L0036:	jsr     _abs
	jsr     tosaddax
	ldy     #$04
	jsr     staxysp
;
; if (distance < best_distance) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 288
	ldy     #$06
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bvc     L003B
	eor     #$80
L003B:	bpl     L0020
;
; best_distance = distance;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 289
	ldy     #$05
	jsr     ldaxysp
	ldy     #$06
	jsr     staxysp
;
; best = i;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 290
	ldy     #$09
	lda     (c_sp),y
	dey
	sta     (c_sp),y
;
; for (i = 0; i < 8; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 282
L0020:	ldy     #$09
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L003C
;
; pursuer_dir_x = dir_x[best];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 293
L001F:	lda     #<(M0001)
	ldx     #>(M0001)
	dey
	clc
	adc     (c_sp),y
	bcc     L0028
	inx
L0028:	ldy     #$00
	jsr     ldaidx
	sta     _pursuer_dir_x
;
; pursuer_dir_y = dir_y[best];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 294
	lda     #<(M0002)
	ldx     #>(M0002)
	ldy     #$08
	clc
	adc     (c_sp),y
	bcc     L0029
	inx
L0029:	ldy     #$00
	jsr     ldaidx
	sta     _pursuer_dir_y
;
; candidate_x = (int)pursuer_x + pursuer_dir_x * PURSUER_PER_TICK * frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 297
L0019:	lda     _pursuer_x
	ldx     _pursuer_x+1
	jsr     pushax
	ldx     #$00
	lda     _pursuer_dir_x
	bpl     L002A
	dex
L002A:	jsr     aslax3
	jsr     pushax
	lda     _frame_ticks
	jsr     tosmula0
	jsr     tosaddax
	ldy     #$02
	jsr     staxysp
;
; candidate_y = (int)pursuer_y + pursuer_dir_y * PURSUER_PER_TICK * frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 298
	lda     _pursuer_y
	ldx     _pursuer_y+1
	jsr     pushax
	ldx     #$00
	lda     _pursuer_dir_y
	bpl     L002B
	dex
L002B:	jsr     aslax3
	jsr     pushax
	lda     _frame_ticks
	jsr     tosmula0
	jsr     tosaddax
	jsr     stax0sp
;
; if (!maze_solid((unsigned char)(candidate_x >> 8), row))
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 299
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0E
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L002C
;
; pursuer_x = (unsigned int)candidate_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 300
	ldy     #$03
	jsr     ldaxysp
	sta     _pursuer_x
	stx     _pursuer_x+1
;
; if (!maze_solid((unsigned char)(pursuer_x >> 8), (unsigned char)(candidate_y >> 8)))
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 301
L002C:	lda     _pursuer_x+1
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L002E
;
; pursuer_y = (unsigned int)candidate_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 302
	jsr     ldax0sp
	sta     _pursuer_y
	stx     _pursuer_y+1
;
; col = (unsigned char)(pursuer_x >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 304
L002E:	lda     _pursuer_x+1
	ldy     #$0E
	sta     (c_sp),y
;
; row = (unsigned char)(pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 305
	lda     _pursuer_y+1
	dey
	sta     (c_sp),y
;
; if (col != pursuer_stuck_col || row != pursuer_stuck_row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 306
	iny
	lda     (c_sp),y
	cmp     _pursuer_stuck_col
	bne     L004E
	dey
	lda     (c_sp),y
	cmp     _pursuer_stuck_row
	beq     L004D
;
; pursuer_stuck_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 307
	iny
L004E:	lda     (c_sp),y
	sta     _pursuer_stuck_col
;
; pursuer_stuck_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 308
	dey
	lda     (c_sp),y
	sta     _pursuer_stuck_row
;
; pursuer_stuck_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 309
	lda     #$00
	sta     _pursuer_stuck_ticks
	sta     _pursuer_stuck_ticks+1
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 310
	jmp     L0034
;
; pursuer_stuck_ticks += frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 311
L004D:	lda     _frame_ticks
	clc
	adc     _pursuer_stuck_ticks
	sta     _pursuer_stuck_ticks
	lda     #$00
	adc     _pursuer_stuck_ticks+1
	sta     _pursuer_stuck_ticks+1
;
; if (pursuer_stuck_ticks >= PURSUER_STUCK_TICKS) respawn_pursuer();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 312
	lda     _pursuer_stuck_ticks
	cmp     #$C8
	lda     _pursuer_stuck_ticks+1
	sbc     #$00
	bcc     L0034
	jsr     _respawn_pursuer
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 314
L0034:	ldy     #$0F
	jmp     addysp

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$FF
	.byte	$00
	.byte	$01
	.byte	$FF
	.byte	$01
	.byte	$FF
	.byte	$00
	.byte	$01
M0002:
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ pursuer_caught_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pursuer_caught_player: near

	.dbg	func, "pursuer_caught_player", "00", static, "_pursuer_caught_player"

.segment	"CODE"

;
; return (player_x >> 8) == (pursuer_x >> 8)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 319
	ldx     #$00
	lda     _player_x+1
;
; && (player_y >> 8) == (pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 320
	cmp     _pursuer_x+1
	bne     L0005
	lda     _player_y+1
	cmp     _pursuer_y+1
	beq     L0006
L0005:	txa
	rts
L0006:	lda     #$01
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 321
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ deploy_decoy (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_deploy_decoy: near

	.dbg	func, "deploy_decoy", "00", static, "_deploy_decoy"

.segment	"CODE"

;
; if (!decoy_available) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 325
	lda     _decoy_available
	beq     L0001
;
; decoy_x = player_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 326
	lda     _player_x+1
	sta     _decoy_x+1
	lda     _player_x
	sta     _decoy_x
;
; decoy_y = player_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 327
	lda     _player_y+1
	sta     _decoy_y+1
	lda     _player_y
	sta     _decoy_y
;
; decoy_active = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 328
	lda     #$01
	sta     _decoy_active
;
; decoy_available = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 329
	lda     #$00
	sta     _decoy_available
;
; decoy_capture_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 330
	sta     _decoy_capture_ticks
;
; decoy_recharge_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 331
	sta     _decoy_recharge_ticks
;
; decoy_active_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 332
	sta     _decoy_active_ticks
	sta     _decoy_active_ticks+1
;
; pursuer_retarget_timer = RETARGET_STALE_TICKS + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 333
	lda     #$33
	sta     _pursuer_retarget_timer
;
; melody_play(DECOY_DEPLOY_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 334
	lda     #<(S0003)
	ldx     #>(S0003)
	jmp     _melody_play
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 335
L0001:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ update_decoy_recharge (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_decoy_recharge: near

	.dbg	func, "update_decoy_recharge", "00", static, "_update_decoy_recharge"
	.dbg	sym, "next", "00", auto, -2

.segment	"CODE"

;
; if (decoy_active) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 341
	jsr     decsp2
	lda     _decoy_active
	beq     L0004
;
; next = decoy_active_ticks + frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 342
	lda     _decoy_active_ticks
	ldx     _decoy_active_ticks+1
	clc
	adc     _frame_ticks
	bcc     L0010
	inx
L0010:	jsr     stax0sp
;
; if (next >= DECOY_ACTIVE_TICKS) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 343
	cmp     #$F4
	txa
	sbc     #$01
	bcc     L0003
;
; decoy_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 344
	lda     #$00
	sta     _decoy_active
;
; decoy_capture_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 345
	sta     _decoy_capture_ticks
;
; decoy_recharge_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 346
	sta     _decoy_recharge_ticks
;
; pursuer_retarget_timer = RETARGET_STALE_TICKS + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 347
	lda     #$33
	sta     _pursuer_retarget_timer
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 348
	jmp     L0004
;
; decoy_active_ticks = next;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 349
L0003:	jsr     ldax0sp
	sta     _decoy_active_ticks
	stx     _decoy_active_ticks+1
;
; if (!decoy_active && decoy_recharge_ticks < DECOY_RECHARGE_TICKS) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 352
L0004:	lda     _decoy_active
	bne     L000B
	lda     _decoy_recharge_ticks
	cmp     #$C8
	bcs     L000B
;
; next = (unsigned int)decoy_recharge_ticks + frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 353
	ldx     #$00
	lda     _decoy_recharge_ticks
	clc
	adc     _frame_ticks
	bcc     L0011
	inx
L0011:	jsr     stax0sp
;
; ? DECOY_RECHARGE_TICKS : (unsigned char)next;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 355
	cmp     #$C8
	txa
	sbc     #$00
	bcc     L0009
	lda     #$C8
	jmp     L0013
L0009:	ldy     #$00
	lda     (c_sp),y
L0013:	sta     _decoy_recharge_ticks
;
; if (decoy_recharge_ticks >= DECOY_RECHARGE_TICKS)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 356
	cmp     #$C8
	bcc     L000B
;
; melody_play(DECOY_READY_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 357
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     _melody_play
;
; if (!decoy_active && decoy_recharge_ticks >= DECOY_RECHARGE_TICKS)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 359
L000B:	lda     _decoy_active
	bne     L0015
	lda     _decoy_recharge_ticks
	cmp     #$C8
	bcc     L0015
;
; decoy_available = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 360
	lda     #$01
	sta     _decoy_available
;
; hud_set_decoy(decoy_recharge_ticks, DECOY_RECHARGE_TICKS);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 361
L0015:	lda     _decoy_recharge_ticks
	jsr     pusha
	lda     #$C8
	jsr     _hud_set_decoy
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 362
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ update_laser (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_laser: near

	.dbg	func, "update_laser", "00", static, "_update_laser"

.segment	"CODE"

;
; laser_elapsed_ticks += frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 366
	lda     _frame_ticks
	clc
	adc     _laser_elapsed_ticks
	sta     _laser_elapsed_ticks
	lda     #$00
	adc     _laser_elapsed_ticks+1
	sta     _laser_elapsed_ticks+1
;
; if (laser_elapsed_ticks < laser_period_ticks) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 367
	lda     _laser_elapsed_ticks
	cmp     _laser_period_ticks
	lda     _laser_elapsed_ticks+1
	sbc     _laser_period_ticks+1
	bcc     L0001
;
; laser_elapsed_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 368
	lda     #$00
	sta     _laser_elapsed_ticks
	sta     _laser_elapsed_ticks+1
;
; sprite3d_build_laser(player_x, player_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 369
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     _sprite3d_build_laser
;
; melody_laser_buzz();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 370
	jmp     _melody_laser_buzz
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 371
L0001:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ start_life (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_life: near

	.dbg	func, "start_life", "00", static, "_start_life"

.segment	"CODE"

;
; if (threat_color_active) COLOR4 = threat_old_color;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 375
	lda     _threat_color_active
	beq     L0003
	lda     _threat_old_color
	sta     $02C8
;
; threat_color_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 376
	lda     #$00
L0003:	sta     _threat_color_active
;
; player_x = PLAYER_START_X;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 377
	ldx     #$06
	lda     #$80
	sta     _player_x
	stx     _player_x+1
;
; player_y = PLAYER_START_Y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 378
	ldx     #$01
	sta     _player_y
	stx     _player_y+1
;
; player_angle = PLAYER_START_ANGLE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 379
	lda     #$00
	sta     _player_angle
	sta     _player_angle+1
;
; place_pursuer_at_start();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 380
	jsr     _place_pursuer_at_start
;
; pursuer_dir_x = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 381
	lda     #$00
	sta     _pursuer_dir_x
;
; pursuer_dir_y = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 382
	sta     _pursuer_dir_y
;
; pursuer_retarget_timer = RETARGET_STALE_TICKS + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 383
	lda     #$33
	sta     _pursuer_retarget_timer
;
; decoy_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 384
	lda     #$00
	sta     _decoy_active
;
; decoy_available = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 385
	lda     #$01
	sta     _decoy_available
;
; decoy_capture_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 386
	lda     #$00
	sta     _decoy_capture_ticks
;
; decoy_recharge_ticks = DECOY_RECHARGE_TICKS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 387
	lda     #$C8
	sta     _decoy_recharge_ticks
;
; decoy_active_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 388
	lda     #$00
	sta     _decoy_active_ticks
	sta     _decoy_active_ticks+1
;
; floor_motion_units = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 389
	sta     _floor_motion_units
	sta     _floor_motion_units+1
;
; sprite3d_clear_all();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 390
	jsr     _sprite3d_clear_all
;
; sprite3d_build_laser(PLAYER_START_X, PLAYER_START_Y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 391
	ldx     #$06
	lda     #$80
	jsr     pushax
	ldx     #$01
	jsr     _sprite3d_build_laser
;
; laser_elapsed_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 392
	lda     #$00
	sta     _laser_elapsed_ticks
	sta     _laser_elapsed_ticks+1
;
; hud_set_decoy(decoy_recharge_ticks, DECOY_RECHARGE_TICKS);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 393
	lda     _decoy_recharge_ticks
	jsr     pusha
	lda     #$C8
	jsr     _hud_set_decoy
;
; melody_laser_buzz();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 394
	jmp     _melody_laser_buzz

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ update_game_hud (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_game_hud: near

	.dbg	func, "update_game_hud", "00", static, "_update_game_hud"

.segment	"CODE"

;
; hud_set_game(lives, level, score, high_score);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 399
	lda     _lives
	jsr     pusha
	lda     _level
	jsr     pusha
	lda     _score
	ldx     _score+1
	jsr     pushax
	lda     _high_score
	ldx     _high_score+1
	jmp     _hud_set_game

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ start_new_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_new_game: near

	.dbg	func, "start_new_game", "00", static, "_start_new_game"

.segment	"CODE"

;
; lives = STARTING_LIVES;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 404
	lda     #$03
	sta     _lives
;
; level = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 405
	lda     #$01
	sta     _level
;
; score = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 406
	lda     #$00
	sta     _score
	sta     _score+1
;
; maze_load_level(level);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 407
	lda     _level
	jsr     _maze_load_level
;
; minimap_build();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 408
	jsr     _minimap_build
;
; minimap_show();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 409
	jsr     _minimap_show
;
; sprite3d_build_targets();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 410
	jsr     _sprite3d_build_targets
;
; sprite3d_locate_exit();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 411
	jsr     _sprite3d_locate_exit
;
; hud_set_targets(sprite3d_targets_left());
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 413
	jsr     _sprite3d_targets_left
	jsr     _hud_set_targets
;
; start_life();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 415
	jsr     _start_life
;
; update_game_hud();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 416
	jmp     _update_game_hud

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ restart_pressed (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_restart_pressed: near

	.dbg	func, "restart_pressed", "00", static, "_restart_pressed"

.segment	"CODE"

;
; return read_key() == KEY_SPACE
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 421
	jsr     _read_key
;
; || *(volatile unsigned char *)JOYSTICK_FIRE0 == 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 422
	cmp     #$21
	beq     L0004
	lda     $D010
	beq     L0004
	ldx     #$00
	txa
	rts
L0004:	lda     #$01
	ldx     #$00
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 423
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ show_end_screen (const char *message, unsigned char size, const char *melody)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_end_screen: near

	.dbg	func, "show_end_screen", "00", static, "_show_end_screen"
	.dbg	sym, "message", "00", auto, 3
	.dbg	sym, "size", "00", auto, 2
	.dbg	sym, "melody", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 427
	jsr     pushax
;
; if (threat_color_active) COLOR4 = threat_old_color;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 428
	lda     _threat_color_active
	beq     L000C
	lda     _threat_old_color
	sta     $02C8
;
; threat_color_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 429
	lda     #$00
L000C:	sta     _threat_color_active
;
; sprite3d_clear_all();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 430
	jsr     _sprite3d_clear_all
;
; view3d_render(player_x, player_y, player_angle);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 431
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     _view3d_render
;
; textplot_print_fullscreen(TEXTPLOT_ALIGN_CENTER, message, 30, 1, size);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 432
	lda     #$01
	jsr     pusha
	ldy     #$07
	jsr     pushwysp
	lda     #$1E
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$07
	lda     (c_sp),y
	jsr     _textplot_print_fullscreen
;
; textplot_print_fullscreen(TEXTPLOT_ALIGN_CENTER, "Press Space or Fire",
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 433
	lda     #$01
	jsr     pusha
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     pushax
;
; 50, 3, TEXTPLOT_SIZE_HALF);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 434
	lda     #$32
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$80
	jsr     _textplot_print_fullscreen
;
; melody_play(melody);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 435
	jsr     ldax0sp
	jsr     _melody_play
;
; while (restart_pressed()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 437
	jmp     L0005
L0003:	jsr     _wait_frame
L0005:	jsr     _restart_pressed
	tax
	bne     L0003
;
; while (!restart_pressed()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 438
	jmp     L0008
L0006:	jsr     _wait_frame
L0008:	jsr     _restart_pressed
	tax
	beq     L0006
;
; while (restart_pressed()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 439
	jmp     L000B
L0009:	jsr     _wait_frame
L000B:	jsr     _restart_pressed
	tax
	bne     L0009
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 440
	jmp     incsp5

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ game_over (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_over: near

	.dbg	func, "game_over", "00", static, "_game_over"

.segment	"CODE"

;
; show_end_screen("Game Over", TEXTPLOT_SIZE_DOUBLE, GAME_OVER_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 444
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     pushax
	lda     #$02
	jsr     pusha
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     _show_end_screen
;
; start_new_game();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 445
	jmp     _start_new_game

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ victory (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_victory: near

	.dbg	func, "victory", "00", static, "_victory"

.segment	"CODE"

;
; show_end_screen("YOU DID IT !!!", TEXTPLOT_SIZE_NORMAL, VICTORY_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 450
	lda     #<(S0008)
	ldx     #>(S0008)
	jsr     pushax
	lda     #$01
	jsr     pusha
	lda     #<(S0009)
	ldx     #>(S0009)
	jsr     _show_end_screen
;
; start_new_game();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 451
	jmp     _start_new_game

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ score_target (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_score_target: near

	.dbg	func, "score_target", "00", static, "_score_target"

.segment	"CODE"

;
; if (score > 65535u - SCORE_PER_TARGET)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 456
	lda     _score
	cmp     #$9C
	lda     _score+1
	sbc     #$FF
	bcc     L0002
;
; score = 65535u;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 457
	lda     #$FF
	sta     _score
	sta     _score+1
;
; else
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 458
	jmp     L0003
;
; score += SCORE_PER_TARGET;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 459
L0002:	lda     #$64
	clc
	adc     _score
	sta     _score
	bcc     L0003
	inc     _score+1
;
; if (score > high_score) high_score = score;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 460
L0003:	lda     _score
	sec
	sbc     _high_score
	sta     tmp1
	lda     _score+1
	sbc     _high_score+1
	ora     tmp1
	bcc     L0005
	beq     L0005
	lda     _score+1
	sta     _high_score+1
	lda     _score
	sta     _high_score
;
; update_game_hud();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 461
L0005:	jmp     _update_game_hud

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ handle_catch (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_catch: near

	.dbg	func, "handle_catch", "00", static, "_handle_catch"

.segment	"CODE"

;
; melody_set_threat_level(0);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 466
	lda     #$00
	jsr     _melody_set_threat_level
;
; melody_play(CAUGHT_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 467
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _melody_play
;
; while (melody_playing()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 468
	jmp     L0004
L0002:	jsr     _wait_frame
L0004:	jsr     _melody_playing
	tax
	bne     L0002
;
; --lives;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 470
	dec     _lives
;
; update_game_hud();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 471
	jsr     _update_game_hud
;
; if (lives == 0)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 472
	lda     _lives
	bne     L0005
;
; game_over();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 473
	jmp     _game_over
;
; start_life();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 475
L0005:	jmp     _start_life

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ update_threat_sound (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_threat_sound: near

	.dbg	func, "update_threat_sound", "00", static, "_update_threat_sound"
	.dbg	sym, "distance", "00", auto, -2
	.dbg	sym, "level_signal", "00", auto, -3

.segment	"CODE"

;
; distance = abs((int)player_x - (int)pursuer_x)
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 483
	jsr     decsp3
	lda     _player_x
	sec
	sbc     _pursuer_x
	pha
	lda     _player_x+1
	sbc     _pursuer_x+1
	tax
	pla
;
; + abs((int)player_y - (int)pursuer_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 484
	jsr     _abs
	jsr     pushax
	lda     _player_y
	sec
	sbc     _pursuer_y
	pha
	lda     _player_y+1
	sbc     _pursuer_y+1
	tax
	pla
	jsr     _abs
	jsr     tosaddax
	ldy     #$01
	jsr     staxysp
;
; if (distance >= THREAT_DISTANCE) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 485
	cmp     #$00
	txa
	sbc     #$10
	bvs     L0003
	eor     #$80
L0003:	bpl     L0002
;
; level_signal = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 486
	lda     #$00
	tay
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 487
	jmp     L000C
;
; level_signal = (unsigned char)((THREAT_DISTANCE - distance) >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 488
L0002:	lda     #$00
	sec
	ldy     #$01
	sbc     (c_sp),y
	lda     #$10
	iny
	sbc     (c_sp),y
	tax
	txa
	cpx     #$80
	ldy     #$00
	sta     (c_sp),y
;
; if (level_signal == 0) level_signal = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 489
	lda     (c_sp),y
	bne     L000F
	lda     #$01
	sta     (c_sp),y
;
; if (level_signal > 15) level_signal = 15;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 490
L000F:	lda     (c_sp),y
	cmp     #$10
	bcc     L0011
	lda     #$0F
L000C:	sta     (c_sp),y
;
; if (level_signal > 10) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 492
L0011:	lda     (c_sp),y
	cmp     #$0B
	bcc     L0008
;
; if (!threat_color_active) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 493
	lda     _threat_color_active
	bne     L0012
;
; threat_old_color = COLOR4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 494
	lda     $02C8
	sta     _threat_old_color
;
; threat_color_active = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 495
	lda     #$01
	sta     _threat_color_active
;
; COLOR4 = COLOR_ORANGE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 497
L0012:	lda     #$4A
	sta     $02C8
;
; } else if (threat_color_active) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 498
	jmp     L0014
L0008:	lda     _threat_color_active
	beq     L0014
;
; COLOR4 = threat_old_color;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 499
	lda     _threat_old_color
	sta     $02C8
;
; threat_color_active = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 500
	sty     _threat_color_active
;
; melody_set_threat_level(level_signal);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 502
L0014:	lda     (c_sp),y
	jsr     _melody_set_threat_level
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 503
	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ handle_level_clear (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_level_clear: near

	.dbg	func, "handle_level_clear", "00", static, "_handle_level_clear"

.segment	"CODE"

;
; melody_set_threat_level(0);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 509
	lda     #$00
	jsr     _melody_set_threat_level
;
; melody_play(LEVEL_CLEAR_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 510
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _melody_play
;
; while (melody_playing()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 511
	jmp     L0004
L0002:	jsr     _wait_frame
L0004:	jsr     _melody_playing
	tax
	bne     L0002
;
; if (level >= LEVEL_MAX) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 513
	lda     _level
	cmp     #$06
	bcc     L0009
;
; victory();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 514
	jmp     _victory
;
; ++level;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 517
L0009:	inc     _level
;
; update_game_hud();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 518
	jsr     _update_game_hud
;
; maze_load_level(level);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 519
	lda     _level
	jsr     _maze_load_level
;
; minimap_build();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 520
	jsr     _minimap_build
;
; minimap_show();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 521
	jsr     _minimap_show
;
; sprite3d_build_targets();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 522
	jsr     _sprite3d_build_targets
;
; sprite3d_locate_exit();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 523
	jsr     _sprite3d_locate_exit
;
; hud_set_targets(sprite3d_targets_left());
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 525
	jsr     _sprite3d_targets_left
	jsr     _hud_set_targets
;
; melody_play(LEVEL_LOAD_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 528
	lda     #<(S000C)
	ldx     #>(S000C)
	jsr     _melody_play
;
; while (melody_playing()) wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 529
	jmp     L0008
L0006:	jsr     _wait_frame
L0008:	jsr     _melody_playing
	tax
	bne     L0006
;
; start_life();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 531
	jmp     _start_life

	.dbg	line
.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"
	.dbg	sym, "key", "00", auto, -1
	.dbg	sym, "ticks_per_second", "00", auto, -2
	.dbg	sym, "prev_tick", "00", auto, -3
	.dbg	sym, "now", "00", auto, -4
	.dbg	sym, "previous_key", "00", auto, -5
	.dbg	sym, "last_tick", "00", auto, -6
	.dbg	sym, "frames", "00", auto, -7

.segment	"CODE"

;
; *(volatile unsigned char *)PBCTL |= 0x04;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 546
	jsr     decsp7
	lda     $D303
	ora     #$04
	sta     $D303
;
; *(volatile unsigned char *)PORTB |= 0x02;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 547
	lda     $D301
	ora     #$02
	sta     $D301
;
; OS.sdmctl = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 548
	lda     #$00
	sta     $022F
;
; ANTIC.dmactl = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 549
	sta     $D400
;
; | *(volatile unsigned char *)RTCLOK_LOW);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 552
	lda     $0014
	ldx     $D20A
	jsr     _srand
;
; splash_screen_show();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 554
	jsr     _splash_screen_show
;
; maze_load_level(1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 556
	lda     #$01
	jsr     _maze_load_level
;
; minimap_build();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 558
	jsr     _minimap_build
;
; sprite3d_build_targets();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 559
	jsr     _sprite3d_build_targets
;
; sprite3d_locate_exit();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 560
	jsr     _sprite3d_locate_exit
;
; splash_screen_rainbow();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 562
	jsr     _splash_screen_rainbow
;
; view3d_init();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 564
	jsr     _view3d_init
;
; minimap_show();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 565
	jsr     _minimap_show
;
; sprite3d_init();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 566
	jsr     _sprite3d_init
;
; melody_install();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 567
	jsr     _melody_install
;
; melody_threat_play("A02A02E12A02A02E12");
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 568
	lda     #<(S000D)
	ldx     #>(S000D)
	jsr     _melody_threat_play
;
; start_life();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 569
	jsr     _start_life
;
; *(volatile unsigned char *)NOCLIK = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 570
	lda     #$01
	sta     $02DB
;
; hud_set_targets(sprite3d_targets_left());
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 572
	jsr     _sprite3d_targets_left
	jsr     _hud_set_targets
;
; textplot_print_fullscreen(TEXTPLOT_ALIGN_LEFT, "DECOY",
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 574
	lda     #$00
	jsr     pusha
	lda     #<(S000E)
	ldx     #>(S000E)
	jsr     pushax
;
; DECOY_BAR_TOP + DECOY_BAR_HEIGHT, 3,
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 575
	lda     #$43
	jsr     pusha
	lda     #$03
	jsr     pusha
;
; TEXTPLOT_SIZE_HALF);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 576
	lda     #$80
	jsr     _textplot_print_fullscreen
;
; update_game_hud();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 577
	jsr     _update_game_hud
;
; melody_play(LEVEL_LOAD_MELODY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 578
	lda     #<(S000F)
	ldx     #>(S000F)
	jsr     _melody_play
;
; ticks_per_second = (get_tv() == AT_PAL) ? 50 : 60;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 580
	jsr     _get_tv
	cmp     #$01
	bne     L0002
	lda     #$32
	jmp     L0020
L0002:	lda     #$3C
L0020:	ldy     #$05
	sta     (c_sp),y
;
; laser_period_ticks = (unsigned int)ticks_per_second * LASER_SECONDS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 581
	ldx     #$00
	lda     (c_sp),y
	jsr     mulax5
	sta     _laser_period_ticks
	stx     _laser_period_ticks+1
;
; laser_elapsed_ticks = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 582
	lda     #$00
	sta     _laser_elapsed_ticks
	sta     _laser_elapsed_ticks+1
;
; prev_tick = *(volatile unsigned char *)RTCLOK_LOW;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 583
	lda     $0014
	dey
	sta     (c_sp),y
;
; last_tick = prev_tick;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 585
	ldy     #$01
	sta     (c_sp),y
;
; frames = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 586
	lda     #$00
	dey
	sta     (c_sp),y
;
; previous_key = 0xFF;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 588
	lda     #$FF
	ldy     #$02
	sta     (c_sp),y
;
; now = *(volatile unsigned char *)RTCLOK_LOW;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 591
L0021:	lda     $0014
	ldy     #$03
	sta     (c_sp),y
;
; frame_ticks = (unsigned char)(now - prev_tick);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 592
	sec
	iny
	sbc     (c_sp),y
	sta     _frame_ticks
;
; if (frame_ticks == 0) frame_ticks = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 593
	lda     _frame_ticks
	bne     L0022
	lda     #$01
;
; else if (frame_ticks > MAX_TICKS) frame_ticks = MAX_TICKS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 594
	jmp     L001F
L0022:	lda     _frame_ticks
	cmp     #$07
	bcc     L000A
	lda     #$06
L001F:	sta     _frame_ticks
;
; prev_tick = now;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 595
L000A:	dey
	lda     (c_sp),y
	iny
	sta     (c_sp),y
;
; key = read_key();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 597
	jsr     _read_key
	ldy     #$06
	sta     (c_sp),y
;
; if (key == KEY_ESC) break;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 598
	cmp     #$1C
	jeq     L002D
;
; if (key == KEY_W) step_forward(1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 599
	lda     (c_sp),y
	cmp     #$2E
	bne     L0024
	lda     #$01
	jsr     _step_forward
;
; else if (key == KEY_S) step_forward(-1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 600
	jmp     L0014
L0024:	lda     (c_sp),y
	cmp     #$3E
	bne     L0026
	lda     #$FF
	jsr     _step_forward
;
; else if (key == KEY_A) player_angle -= TURN_PER_TICK * frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 601
	jmp     L0014
L0026:	lda     (c_sp),y
	cmp     #$3F
	bne     L0028
	lda     _frame_ticks
	jsr     pusha0
	ldx     #$01
	lda     #$90
	jsr     tosumulax
	eor     #$FF
	sec
	adc     _player_angle
	sta     _player_angle
	txa
	eor     #$FF
	adc     _player_angle+1
	sta     _player_angle+1
;
; else if (key == KEY_D) player_angle += TURN_PER_TICK * frame_ticks;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 602
	jmp     L0014
L0028:	lda     (c_sp),y
	cmp     #$3A
	bne     L002A
	lda     _frame_ticks
	jsr     pusha0
	ldx     #$01
	lda     #$90
	jsr     tosumulax
	clc
	adc     _player_angle
	sta     _player_angle
	txa
	adc     _player_angle+1
	sta     _player_angle+1
;
; else if (key == KEY_SPACE && previous_key != KEY_SPACE) deploy_decoy();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 603
	jmp     L0014
L002A:	lda     (c_sp),y
	cmp     #$21
	bne     L002E
	ldy     #$02
	lda     (c_sp),y
	cmp     #$21
	beq     L0014
	jsr     _deploy_decoy
;
; previous_key = key;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 604
L0014:	ldy     #$06
L002E:	lda     (c_sp),y
	ldy     #$02
	sta     (c_sp),y
;
; update_decoy_recharge();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 606
	jsr     _update_decoy_recharge
;
; update_laser();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 607
	jsr     _update_laser
;
; move_pursuer();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 608
	jsr     _move_pursuer
;
; update_threat_sound();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 609
	jsr     _update_threat_sound
;
; if (pursuer_caught_player() || sprite3d_hit_laser(player_x, player_y))
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 610
	jsr     _pursuer_caught_player
	tax
	bne     L0019
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     _sprite3d_hit_laser
	tax
	beq     L0018
;
; handle_catch();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 611
L0019:	jsr     _handle_catch
;
; if (sprite3d_collect(player_x, player_y)) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 612
L0018:	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     _sprite3d_collect
	tax
	beq     L001B
;
; hud_set_targets(sprite3d_targets_left());
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 614
	jsr     _sprite3d_targets_left
	jsr     _hud_set_targets
;
; score_target();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 616
	jsr     _score_target
;
; melody_pickup();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 617
	jsr     _melody_pickup
;
; if (sprite3d_targets_left() == 0) maze_set_exit_open(1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 619
L001B:	jsr     _sprite3d_targets_left
	cmp     #$00
	bne     L001C
	lda     #$01
	jsr     _maze_set_exit_open
;
; if (sprite3d_reached_exit(player_x, player_y)) handle_level_clear();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 620
L001C:	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     _sprite3d_reached_exit
	tax
	beq     L001D
	jsr     _handle_level_clear
;
; view3d_render(player_x, player_y, player_angle);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 622
L001D:	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     _view3d_render
;
; sprite3d_draw_targets(player_x, player_y, player_angle);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 623
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     _sprite3d_draw_targets
;
; sprite3d_draw_pursuer(player_x, player_y, player_angle,
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 624
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     pushax
;
; pursuer_x, pursuer_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 625
	lda     _pursuer_x
	ldx     _pursuer_x+1
	jsr     pushax
	lda     _pursuer_y
	ldx     _pursuer_y+1
	jsr     _sprite3d_draw_pursuer
;
; sprite3d_draw_decoy(decoy_active, player_x, player_y, player_angle,
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 626
	lda     _decoy_active
	jsr     pusha
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     pushax
;
; decoy_x, decoy_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 627
	lda     _decoy_x
	ldx     _decoy_x+1
	jsr     pushax
	lda     _decoy_y
	ldx     _decoy_y+1
	jsr     _sprite3d_draw_decoy
;
; minimap_update(player_x, player_y, player_angle,
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 628
	lda     _player_x
	ldx     _player_x+1
	jsr     pushax
	lda     _player_y
	ldx     _player_y+1
	jsr     pushax
	lda     _player_angle
	ldx     _player_angle+1
	jsr     pushax
;
; pursuer_x, pursuer_y);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 629
	lda     _pursuer_x
	ldx     _pursuer_x+1
	jsr     pushax
	lda     _pursuer_y
	ldx     _pursuer_y+1
	jsr     _minimap_update
;
; ++frames;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 632
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; now = *(volatile unsigned char *)RTCLOK_LOW;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 633
	lda     $0014
	ldy     #$03
	sta     (c_sp),y
;
; if ((unsigned char)(now - last_tick) >= ticks_per_second) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 634
	sec
	ldy     #$01
	sbc     (c_sp),y
	ldy     #$05
	cmp     (c_sp),y
	bcc     L001E
;
; hud_set_fps(frames);
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 635
	ldy     #$00
	lda     (c_sp),y
	jsr     _hud_set_fps
;
; frames = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 636
	lda     #$00
	tay
	sta     (c_sp),y
;
; last_tick = now;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 637
	ldy     #$03
	lda     (c_sp),y
	ldy     #$01
	sta     (c_sp),y
;
; wait_frame();
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 640
L001E:	jsr     _wait_frame
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 641
	jmp     L0021
;
; *(volatile unsigned char *)0x02E5 = startup_memtop[0];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 642
L002D:	lda     _startup_memtop
	sta     $02E5
;
; *(volatile unsigned char *)0x02E6 = startup_memtop[1];
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 643
	lda     _startup_memtop+1
	sta     $02E6
;
; *(volatile unsigned char *)PORTB = startup_portb;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 644
	lda     _startup_portb
	sta     $D301
;
; return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 645
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\chased3d.c", 646
	rts

	.dbg	line
.endproc

