;
; File generated by cc65 v 2.19 - Git 547d923
;
	.fopt		compiler,"cc65 v 2.19 - Git 547d923"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "C:\Users\Alex\Chased3D\maze.c", 7236, 1788475720
	.dbg		file, "C:\tools\cc65\include/fcntl.h", 3550, 1786840065
	.dbg		file, "C:\tools\cc65\include/unistd.h", 4340, 1786840065
	.dbg		file, "C:\Users\Alex\Chased3D/maze.h", 550, 1787868964
	.import		_open
	.import		_close
	.import		_read
	.export		_maze_map
	.export		_maze_row_lo
	.export		_maze_row_hi
	.export		_maze_exit_col
	.export		_maze_exit_row
	.export		_maze_exit_found
	.export		_maze_exit_open
	.export		_maze_load_level
	.export		_maze_solid
	.export		_maze_set_exit_open

.segment	"RODATA"

_level1_data:
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
S0006:
	.byte	$44,$3A,$4C,$33,$2E,$43,$53,$56,$00
S0007:
	.byte	$44,$3A,$4C,$34,$2E,$43,$53,$56,$00
S0008:
	.byte	$44,$3A,$4C,$35,$2E,$43,$53,$56,$00
S0005:
	.byte	$44,$3A,$4C,$32,$2E,$43,$53,$56,$00

.segment	"BSS"

.segment	"AUXBSS"
.segment	"BSS"
.segment	"HIGHBSS"
.segment	"BSS"
.segment	"HIGHBSS"
_maze_map:
	.res	1180,$00
_maze_row_lo:
	.res	59,$00
_maze_row_hi:
	.res	59,$00
.segment	"BSS"
_maze_exit_col:
	.res	1,$00
_maze_exit_row:
	.res	1,$00
_maze_exit_found:
	.res	1,$00
_maze_exit_open:
	.res	1,$00
.segment	"AUXBSS"
_level_buffer:
	.res	64,$00
_level_file:
	.res	2,$00
_level_buffer_pos:
	.res	1,$00
_level_buffer_len:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ maze_load_level (unsigned char requested_level)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_maze_load_level: near

	.dbg	func, "maze_load_level", "00", static, "_maze_load_level"
	.dbg	sym, "requested_level", "00", auto, 0
	.dbg	sym, "level_name", "00", auto, -2
	.dbg	sym, "row", "00", auto, -3
	.dbg	sym, "col", "00", auto, -4
	.dbg	sym, "tile", "00", auto, -5
	.dbg	sym, "ch", "00", auto, -7

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 124
	jsr     pusha
;
; clear_map();
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 131
	jsr     decsp7
	jsr     _clear_map
;
; maze_exit_open = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 132
	lda     #$00
	sta     _maze_exit_open
;
; maze_exit_found = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 133
	sta     _maze_exit_found
;
; if (requested_level <= 1) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 134
	ldy     #$07
	lda     (c_sp),y
	cmp     #$02
	bcs     L0064
;
; for (row = 0; row < MAZE_H; ++row)
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 135
	lda     #$00
	ldy     #$04
L005A:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0076
;
; for (col = 0; col < MAZE_W; ++col)
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 136
	lda     #$00
	dey
L0059:	sta     (c_sp),y
	cmp     #$14
	bcs     L0005
;
; maze_map[row][col] = level1_data[row][col];
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 137
	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0053
	inx
L0053:	jsr     pushax
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_level1_data)
	sta     ptr1
	txa
	adc     #>(_level1_data)
	sta     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	jsr     staspidx
;
; for (col = 0; col < MAZE_W; ++col)
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 136
	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0059
;
; for (row = 0; row < MAZE_H; ++row)
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 135
L0005:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L005A
;
; } else if (requested_level == 2) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 138
L0064:	lda     (c_sp),y
	cmp     #$02
	jne     L0069
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 142
	lda     #$00
	ldy     #$04
L005D:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0076
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 143
	lda     #$00
	dey
L005C:	sta     (c_sp),y
	cmp     #$14
	bcs     L000F
;
; tile = level1_data[row][col];
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 144
	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_level1_data)
	sta     ptr1
	txa
	adc     #>(_level1_data)
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$02
	sta     (c_sp),y
;
; if (tile == 3) tile = 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 145
	cmp     #$03
	bne     L0066
	lda     #$04
;
; else if (tile == 4) tile = 3;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 146
	jmp     L005B
L0066:	lda     (c_sp),y
	cmp     #$04
	bne     L0067
	lda     #$03
L005B:	sta     (c_sp),y
;
; maze_map[MAZE_H - 1 - row][MAZE_W - 1 - col] = tile;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 147
L0067:	lda     #$3A
	sec
	ldy     #$04
	sbc     (c_sp),y
	ldx     #$00
	bcs     L0051
	dex
L0051:	jsr     pushax
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	lda     #$13
	sec
	ldy     #$03
	sbc     (c_sp),y
	ldx     #$00
	bcs     L0052
	dex
L0052:	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	dey
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 143
	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L005C
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 142
L000F:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L005D
;
; if (requested_level == 3) level_name = "D:L2.CSV";
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 151
L0069:	lda     (c_sp),y
	cmp     #$03
	bne     L006B
	lda     #<(S0005)
	ldx     #>(S0005)
;
; else if (requested_level == 4) level_name = "D:L3.CSV";
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 152
	jmp     L007D
L006B:	lda     (c_sp),y
	cmp     #$04
	bne     L006D
	lda     #<(S0006)
	ldx     #>(S0006)
;
; else if (requested_level == 5) level_name = "D:L4.CSV";
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 153
	jmp     L007D
L006D:	lda     (c_sp),y
	cmp     #$05
	bne     L001D
	lda     #<(S0007)
	ldx     #>(S0007)
;
; else level_name = "D:L5.CSV";
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 154
	jmp     L007D
L001D:	lda     #<(S0008)
	ldx     #>(S0008)
L007D:	ldy     #$05
	jsr     staxysp
;
; level_file = open(level_name, O_RDONLY);
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 155
	jsr     pushax
	lda     #$01
	jsr     pusha0
	ldy     #$04
	jsr     _open
	sta     _level_file
	stx     _level_file+1
;
; if (level_file < 0) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 156
	cpx     #$80
	jcs     L0046
;
; level_buffer_pos = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 157
	lda     #$00
	sta     _level_buffer_pos
;
; level_buffer_len = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 158
	sta     _level_buffer_len
;
; do { ch = read_level_byte(); } while (ch >= 0 && ch != '\n' && ch != '\r');
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 159
L0020:	jsr     _read_level_byte
	jsr     stax0sp
	txa
	bmi     L0055
	ldy     #$01
	lda     (c_sp),y
	bne     L007E
	dey
	lda     (c_sp),y
	cmp     #$9B
	beq     L0055
	iny
L007E:	lda     (c_sp),y
	bne     L0020
	dey
	lda     (c_sp),y
	cmp     #$0D
	bne     L0020
;
; if (ch == '\r') ch = read_level_byte();
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 160
L0055:	ldy     #$01
	lda     (c_sp),y
	bne     L006E
	dey
	lda     (c_sp),y
	cmp     #$0D
	bne     L006E
	jsr     _read_level_byte
	jsr     stax0sp
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 161
L006E:	lda     #$00
	ldy     #$04
L0060:	sta     (c_sp),y
	cmp     #$3B
	jcs     L002B
;
; do { ch = read_level_byte(); } while (ch >= 0 && ch != ';');
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 162
L002D:	jsr     _read_level_byte
	jsr     stax0sp
	txa
	bmi     L0056
	ldy     #$01
	lda     (c_sp),y
	bne     L002D
	dey
	lda     (c_sp),y
	cmp     #$3B
	bne     L002D
;
; if (ch < 0) { close(level_file); return; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 163
L0056:	jsr     ldax0sp
	cpx     #$80
	lda     #$00
	bcc     L0070
	lda     _level_file
	ldx     _level_file+1
	jsr     _close
	jmp     incsp8
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 164
L0070:	ldy     #$03
L005F:	sta     (c_sp),y
	cmp     #$14
	bcs     L002C
;
; do { ch = read_level_byte(); } while (ch >= 0 && (ch < '0' || ch > '6'));
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 165
L0039:	jsr     _read_level_byte
	jsr     stax0sp
	txa
	bmi     L0057
	jsr     ldax0sp
	cmp     #$30
	txa
	sbc     #$00
	bvc     L003E
	eor     #$80
L003E:	bmi     L0039
	jsr     ldax0sp
	cmp     #$37
	txa
	sbc     #$00
	bvs     L0040
	eor     #$80
L0040:	bmi     L0039
;
; if (ch < 0) { close(level_file); return; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 166
L0057:	jsr     ldax0sp
	cpx     #$80
	bcc     L0044
	lda     _level_file
	ldx     _level_file+1
	jsr     _close
	jmp     incsp8
;
; maze_map[row][col] = (unsigned char)(ch - '0');
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 167
L0044:	ldy     #$04
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0054
	inx
L0054:	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$30
	jsr     decaxy
	ldy     #$00
	sta     (ptr1),y
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 164
	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L005F
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 161
L002C:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0060
;
; close(level_file);
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 170
L002B:	lda     _level_file
	ldx     _level_file+1
	jsr     _close
;
; for (row = 0; row < MAZE_H && !maze_exit_found; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 173
L0076:	lda     #$00
	ldy     #$04
L0062:	sta     (c_sp),y
	cmp     #$3B
	bcs     L0046
	lda     _maze_exit_found
	bne     L0046
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 174
	dey
L0061:	sta     (c_sp),y
	cmp     #$14
	bcs     L0047
;
; if (maze_map[row][col] != 5) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 175
	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$05
	bne     L004E
;
; maze_exit_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 176
	ldy     #$03
	lda     (c_sp),y
	sta     _maze_exit_col
;
; maze_exit_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 177
	iny
	lda     (c_sp),y
	sta     _maze_exit_row
;
; maze_exit_found = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 178
	lda     #$01
	sta     _maze_exit_found
;
; break;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 179
	jmp     L007B
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 174
L004E:	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0061
;
; for (row = 0; row < MAZE_H && !maze_exit_found; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 173
L0047:	iny
L007B:	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0062
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 182
L0046:	jmp     incsp8

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ maze_solid (unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_maze_solid: near

	.dbg	func, "maze_solid", "00", static, "_maze_solid"
	.dbg	sym, "x", "00", auto, 1
	.dbg	sym, "y", "00", auto, 0
	.dbg	sym, "tile", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 190
	jsr     pusha
;
; if (x >= MAZE_W || y >= MAZE_H) return 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 193
	jsr     decsp1
	ldy     #$02
	lda     (c_sp),y
	cmp     #$14
	bcs     L000C
	dey
	lda     (c_sp),y
	cmp     #$3B
	bcs     L000C
	jmp     L000E
L000C:	ldx     #$00
	jmp     L0012
;
; tile = maze_map[y][x];
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 194
L000E:	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	sta     (c_sp),y
;
; if (tile == 5) return maze_exit_open ? 0 : 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 195
	ldx     #$00
	lda     (c_sp),y
	cmp     #$05
	bne     L0011
	lda     _maze_exit_open
	beq     L0012
	txa
	jmp     incsp3
;
; return (tile == 1 || tile == 2) ? 1 : 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 196
L0011:	lda     (c_sp),y
	cmp     #$01
	beq     L0001
	cmp     #$02
	beq     L0012
	txa
	jmp     incsp3
L0012:	lda     #$01
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 197
L0001:	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ maze_set_exit_open (unsigned char open)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_maze_set_exit_open: near

	.dbg	func, "maze_set_exit_open", "00", static, "_maze_set_exit_open"
	.dbg	sym, "open", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 185
	jsr     pusha
;
; maze_exit_open = open;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 186
	ldy     #$00
	lda     (c_sp),y
	sta     _maze_exit_open
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 187
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ clear_map (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_map: near

	.dbg	func, "clear_map", "00", static, "_clear_map"
	.dbg	sym, "row", "00", auto, -1
	.dbg	sym, "col", "00", auto, -2
	.dbg	sym, "addr", "00", auto, -4

.segment	"CODE"

;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 94
	jsr     decsp4
	lda     #$00
	ldy     #$03
L0016:	sta     (c_sp),y
	cmp     #$3B
	bcs     L001A
;
; addr = (unsigned int)maze_map[row];
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 95
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	tay
	txa
	adc     #>(_maze_map)
	tax
	tya
	jsr     stax0sp
;
; maze_row_lo[row] = (unsigned char)addr;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 96
	ldy     #$03
	lda     (c_sp),y
	tax
	ldy     #$00
	lda     (c_sp),y
	sta     _maze_row_lo,x
;
; maze_row_hi[row] = (unsigned char)(addr >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 97
	lda     #<(_maze_row_hi)
	ldx     #>(_maze_row_hi)
	ldy     #$03
	clc
	adc     (c_sp),y
	bcc     L0007
	inx
L0007:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	dey
	sta     (ptr1),y
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 94
	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0016
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 100
L001A:	lda     #$00
L0019:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0009
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 101
	lda     #$00
	dey
L0018:	sta     (c_sp),y
	cmp     #$14
	bcs     L000A
;
; if (row == 0 || row == MAZE_H - 1 || col == 0 || col == MAZE_W - 1)
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 102
	iny
	lda     (c_sp),y
	beq     L001D
	cmp     #$3A
	beq     L001D
	dey
	lda     (c_sp),y
	beq     L001B
	cmp     #$13
	bne     L0010
;
; maze_map[row][col] = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 103
L001B:	iny
L001D:	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0014
	inx
L0014:	sta     ptr1
	stx     ptr1+1
	lda     #$01
;
; else
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 104
	jmp     L001C
;
; maze_map[row][col] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 105
L0010:	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0015
	inx
L0015:	sta     ptr1
	stx     ptr1+1
	lda     #$00
L001C:	ldy     #$00
	sta     (ptr1),y
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 101
	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0018
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 100
L000A:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0019
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 108
L0009:	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; int __near__ read_level_byte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_level_byte: near

	.dbg	func, "read_level_byte", "00", static, "_read_level_byte"
	.dbg	sym, "count", "00", auto, -2

.segment	"CODE"

;
; if (level_buffer_pos >= level_buffer_len) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 114
	jsr     decsp2
	lda     _level_buffer_pos
	cmp     _level_buffer_len
	bcc     L0007
;
; count = read(level_file, level_buffer, LEVEL_BUFFER_SIZE);
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 115
	lda     _level_file
	ldx     _level_file+1
	jsr     pushax
	lda     #<(_level_buffer)
	ldx     #>(_level_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$40
	jsr     _read
	jsr     stax0sp
;
; if (count <= 0) return -1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 116
	cmp     #$01
	txa
	sbc     #$00
	bvc     L0004
	eor     #$80
L0004:	asl     a
	lda     #$00
	bcc     L0006
	ldx     #$FF
	txa
	jmp     incsp2
;
; level_buffer_pos = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 117
L0006:	sta     _level_buffer_pos
;
; level_buffer_len = (unsigned char)count;
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 118
	tay
	lda     (c_sp),y
	sta     _level_buffer_len
;
; return level_buffer[level_buffer_pos++];
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 120
L0007:	lda     _level_buffer_pos
	inc     _level_buffer_pos
	sta     ptr1
	clc
	lda     #>(_level_buffer)
	sta     ptr1+1
	ldy     #<(_level_buffer)
	ldx     #$00
	lda     (ptr1),y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\maze.c", 121
	jmp     incsp2

	.dbg	line
.endproc

