;
; File generated by cc65 v 2.19 - Git 547d923
;
	.fopt		compiler,"cc65 v 2.19 - Git 547d923"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "C:\Users\Alex\Chased3D\sprite3d.c", 18624, 1787958368
	.dbg		file, "C:\tools\cc65\include/atari.h", 22152, 1786840064
	.dbg		file, "C:\tools\cc65\include/_atarios.h", 40084, 1786840064
	.dbg		file, "C:\tools\cc65\include/_gtia.h", 13839, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pbi.h", 3143, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pokey.h", 11376, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pia.h", 3044, 1786840064
	.dbg		file, "C:\tools\cc65\include/_antic.h", 11827, 1786840064
	.dbg		file, "C:\tools\cc65\include/stdlib.h", 6948, 1786840065
	.dbg		file, "C:\Users\Alex\Chased3D/maze.h", 550, 1787868964
	.dbg		file, "C:\Users\Alex\Chased3D/trig3d.h", 333, 1787781160
	.dbg		file, "C:\Users\Alex\Chased3D/view3d.h", 1299, 1788211140
	.dbg		file, "C:\Users\Alex\Chased3D/sprite3d.h", 910, 1787954059
	.dbg		sym, "maze_map", "00", extern, "_maze_map"
	.dbg		sym, "maze_exit_col", "00", extern, "_maze_exit_col"
	.dbg		sym, "maze_exit_row", "00", extern, "_maze_exit_row"
	.dbg		sym, "maze_exit_found", "00", extern, "_maze_exit_found"
	.dbg		sym, "sin3d", "00", extern, "_sin3d"
	.dbg		sym, "col_dist", "00", extern, "_col_dist"
	.import		_rand
	.import		_maze_map
	.import		_maze_exit_col
	.import		_maze_exit_row
	.import		_maze_exit_found
	.import		_maze_solid
	.import		_sin3d
	.import		_view3d_wall_height
	.import		_col_dist
	.export		_sprite3d_init
	.export		_sprite3d_build_targets
	.export		_sprite3d_build_laser
	.export		_sprite3d_locate_exit
	.export		_sprite3d_draw_targets
	.export		_sprite3d_draw_pursuer
	.export		_sprite3d_draw_decoy
	.export		_sprite3d_collect
	.export		_sprite3d_hit_laser
	.export		_sprite3d_targets_left
	.export		_sprite3d_clear_all
	.export		_sprite3d_reached_exit

.segment	"RODATA"

.segment	"PAGE6DATA"
_target_sprite:
	.byte	$E1
	.byte	$92
	.byte	$4C
	.byte	$4A
	.byte	$31
	.byte	$31
	.byte	$4D
	.byte	$83
	.byte	$80
	.byte	$80
	.byte	$80
	.byte	$80
	.byte	$80
	.byte	$80
	.byte	$FF
	.byte	$FF
_pursuer_sprite:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$99
	.byte	$BD
	.byte	$FF
	.byte	$BD
	.byte	$99
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_decoy_sprite:
	.byte	$12
	.byte	$16
	.byte	$18
	.byte	$3C
	.byte	$3C
	.byte	$18
	.byte	$68
	.byte	$48
_exit_sprite:
	.byte	$18
	.byte	$3C
	.byte	$7E
	.byte	$FF
	.byte	$FF
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
_laser_sprite:
	.byte	$00
	.byte	$81
	.byte	$24
	.byte	$5A
	.byte	$18
	.byte	$7E
	.byte	$3C
	.byte	$FF
	.byte	$FF
	.byte	$3C
	.byte	$7E
	.byte	$18
	.byte	$5A
	.byte	$24
	.byte	$81
	.byte	$00
.segment	"RODATA"

.segment	"BSS"

.segment	"PMGRAM"
.segment	"BSS"
.segment	"PMGRAM"
_pmg_ram:
	.res	1024,$00
.segment	"BSS"
_exit_px:
	.res	2,$00
_exit_py:
	.res	2,$00
_laser_px:
	.res	2,$00
_laser_py:
	.res	2,$00
_laser_found:
	.res	1,$00
_target_px:
	.res	48,$00
_target_py:
	.res	48,$00
_target_active:
	.res	24,$00
_target_count:
	.res	1,$00
_targets_left:
	.res	1,$00
_cand_dist:
	.res	6,$00
_cand_x:
	.res	3,$00
_cand_top:
	.res	3,$00
_cand_height:
	.res	3,$00
_cand_count:
	.res	1,$00
_last_used:
	.res	1,$00
_projected_x:
	.res	1,$00
_projected_top:
	.res	1,$00
_projected_height:
	.res	1,$00
_projected_dist:
	.res	2,$00
_cand_limit:
	.res	1,$00
_player_clear_top:
	.res	4,$00
_player_clear_height:
	.res	4,$00
_decoy_clear_top:
	.res	1,$00
_decoy_clear_height:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ sprite3d_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_init: near

	.dbg	func, "sprite3d_init", "00", static, "_sprite3d_init"
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "player", "00", auto, -3

.segment	"CODE"

;
; for (i = 0; i < sizeof(pmg_ram); ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 113
	jsr     decsp3
	ldx     #$00
	txa
	ldy     #$01
	jsr     staxysp
L0002:	ldy     #$02
	jsr     ldaxysp
	cpx     #$04
	bcs     L0003
;
; pmg_ram[i] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 114
	ldy     #$02
	jsr     ldaxysp
	clc
	adc     #<(_pmg_ram)
	sta     ptr1
	txa
	adc     #>(_pmg_ram)
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
;
; for (i = 0; i < sizeof(pmg_ram); ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 113
	iny
	tax
	tya
	jsr     addeqysp
	jmp     L0002
;
; ANTIC.pmbase = (unsigned char)((unsigned int)pmg_ram >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 117
L0003:	ldx     #>(_pmg_ram)
	stx     $D407
;
; OS.sdmctl = 0x2E;                   /* normal playfield, DL, player+missile DMA */
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 118
	lda     #$2E
	sta     $022F
;
; ANTIC.dmactl = OS.sdmctl;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 119
	sta     $D400
;
; GTIA_WRITE.gractl = 0x03;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 120
	lda     #$03
	sta     $D01D
;
; OS.gprior = 0x11;                   /* players in front + missiles as Player 4 */
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 121
	lda     #$11
	sta     $026F
;
; GTIA_WRITE.prior = OS.gprior;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 122
	sta     $D01B
;
; OS.color3 = DECOY_COLOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 123
	lda     #$9A
	sta     $02C7
;
; GTIA_WRITE.colpf3 = DECOY_COLOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 124
	sta     $D019
;
; for (player = 0; player < PMG_PLAYERS; ++player) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 126
	lda     #$00
	tay
L0010:	sta     (c_sp),y
	cmp     #$04
	bcs     L0014
;
; *(volatile unsigned char *)(SIZEP0 + player) = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 127
	lda     (c_sp),y
	tay
	lda     #$00
	sta     $D008,y
;
; *(volatile unsigned char *)(PCOLR0 + player) =
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 128
	ldx     #$02
	lda     #$C0
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L000B
	inx
;
; player == 0 ? PURSUER_COLOR : TARGET_COLOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 129
L000B:	sta     ptr1
	stx     ptr1+1
	lda     (c_sp),y
	bne     L0011
	lda     #$34
	jmp     L0013
L0011:	lda     #$1E
L0013:	sta     (ptr1),y
;
; player_clear_top[player] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 130
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _player_clear_top,y
;
; player_clear_height[player] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 131
	tay
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _player_clear_height,y
;
; for (player = 0; player < PMG_PLAYERS; ++player) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 126
	tay
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0010
;
; decoy_clear_top = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 133
L0014:	tya
	sta     _decoy_clear_top
;
; decoy_clear_height = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 134
	sta     _decoy_clear_height
;
; last_used = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 135
	sta     _last_used
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 136
	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_build_targets (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_build_targets: near

	.dbg	func, "sprite3d_build_targets", "00", static, "_sprite3d_build_targets"
	.dbg	sym, "row", "00", auto, -1
	.dbg	sym, "col", "00", auto, -2

.segment	"CODE"

;
; target_count = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 145
	jsr     decsp2
	lda     #$00
	sta     _target_count
;
; for (row = 0; row + 1 < MAZE_H && target_count < MAX_TARGETS; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 146
	ldy     #$01
L001A:	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	cmp     #$3B
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	jpl     L0025
	lda     _target_count
	cmp     #$18
	jcs     L0025
;
; for (col = 0; col < MAZE_W && target_count < MAX_TARGETS; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 147
	lda     #$00
	dey
L0019:	sta     (c_sp),y
	cmp     #$14
	jcs     L0004
	lda     _target_count
	cmp     #$18
	jcs     L0004
;
; if (maze_map[row][col] != 3 || maze_map[row + 1][col] != 4) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 148
	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$03
	bne     L000C
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	jsr     pushax
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$04
	bne     L000C
	ldx     #$00
;
; target_px[target_count] = ((unsigned int)col << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 149
	lda     _target_count
	asl     a
	bcc     L001B
	inx
	clc
L001B:	adc     #<(_target_px)
	sta     ptr1
	txa
	adc     #>(_target_px)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	tax
	lda     #$80
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; target_py[target_count] = (unsigned int)(row + 1) << 8;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 150
	ldx     #$00
	lda     _target_count
	asl     a
	bcc     L001C
	inx
	clc
L001C:	adc     #<(_target_py)
	sta     ptr1
	txa
	adc     #>(_target_py)
	sta     ptr1+1
	lda     (c_sp),y
	clc
	adc     #$01
	tax
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; target_active[target_count] = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 151
	ldy     _target_count
	lda     #$01
	sta     _target_active,y
;
; ++target_count;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 152
	inc     _target_count
;
; for (col = 0; col < MAZE_W && target_count < MAX_TARGETS; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 147
L000C:	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0019
;
; for (row = 0; row + 1 < MAZE_H && target_count < MAX_TARGETS; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 146
L0004:	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L001A
;
; targets_left = target_count;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 155
L0025:	lda     _target_count
	sta     _targets_left
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 156
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_build_laser (unsigned int avoid_x, unsigned int avoid_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_build_laser: near

	.dbg	func, "sprite3d_build_laser", "00", static, "_sprite3d_build_laser"
	.dbg	sym, "avoid_x", "00", auto, 2
	.dbg	sym, "avoid_y", "00", auto, 0
	.dbg	sym, "row", "00", auto, -1
	.dbg	sym, "col", "00", auto, -2
	.dbg	sym, "count", "00", auto, -3
	.dbg	sym, "fallback_col", "00", auto, -4
	.dbg	sym, "fallback_row", "00", auto, -5
	.dbg	sym, "fallback_found", "00", auto, -6
	.dbg	sym, "old_col", "00", auto, -7
	.dbg	sym, "old_row", "00", auto, -8

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 160
	jsr     pushax
;
; old_col = (unsigned char)(laser_px >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 170
	jsr     decsp8
	lda     _laser_px+1
	ldy     #$01
	sta     (c_sp),y
;
; old_row = (unsigned char)(laser_py >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 171
	lda     _laser_py+1
	dey
	sta     (c_sp),y
;
; count = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 172
	tya
	ldy     #$05
	sta     (c_sp),y
;
; fallback_found = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 173
	ldy     #$02
	sta     (c_sp),y
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 174
	ldy     #$07
L001B:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0003
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 175
	lda     #$00
	dey
L001A:	sta     (c_sp),y
	cmp     #$14
	jcs     L0004
;
; if (maze_map[row][col] != 6) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 176
	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_maze_map)
	sta     ptr1
	txa
	adc     #>(_maze_map)
	sta     ptr1+1
	ldy     #$06
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$06
	bne     L0008
;
; if (!fallback_found) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 177
	ldy     #$02
	lda     (c_sp),y
	bne     L000B
;
; fallback_col = col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 178
	ldy     #$06
	lda     (c_sp),y
	ldy     #$04
	sta     (c_sp),y
;
; fallback_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 179
	ldy     #$07
	lda     (c_sp),y
	ldy     #$03
	sta     (c_sp),y
;
; fallback_found = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 180
	lda     #$01
	dey
	sta     (c_sp),y
;
; if (laser_found && col == old_col && row == old_row) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 182
L000B:	lda     _laser_found
	beq     L000C
	ldy     #$06
	lda     (c_sp),y
	ldy     #$01
	cmp     (c_sp),y
	bne     L000C
	ldy     #$07
	lda     (c_sp),y
	ldy     #$00
	cmp     (c_sp),y
	beq     L0008
;
; if (col == (unsigned char)(avoid_x >> 8)
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 183
L000C:	ldy     #$0B
	lda     (c_sp),y
;
; && row == (unsigned char)(avoid_y >> 8)) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 184
	ldy     #$06
	cmp     (c_sp),y
	bne     L0010
	ldy     #$09
	lda     (c_sp),y
	ldy     #$07
	cmp     (c_sp),y
	beq     L0008
;
; ++count;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 185
L0010:	ldy     #$05
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; if ((unsigned int)rand() % count != 0) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 186
	jsr     _rand
	jsr     pushax
	ldy     #$07
	lda     (c_sp),y
	jsr     tosumoda0
	cpx     #$00
	bne     L0008
	cmp     #$00
	bne     L0008
;
; laser_px = ((unsigned int)col << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 187
	ldy     #$06
	lda     (c_sp),y
	sta     _laser_px+1
	lda     #$80
	sta     _laser_px
;
; laser_py = ((unsigned int)row << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 188
	iny
	lda     (c_sp),y
	sta     _laser_py+1
	lda     #$80
	sta     _laser_py
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 175
L0008:	ldy     #$06
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001A
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 174
L0004:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001B
;
; if (count != 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 191
L0003:	ldy     #$05
	lda     (c_sp),y
;
; } else if (fallback_found) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 193
	bne     L0023
	ldy     #$02
	lda     (c_sp),y
	beq     L001C
;
; laser_px = ((unsigned int)fallback_col << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 194
	ldy     #$04
	lda     (c_sp),y
	sta     _laser_px+1
	lda     #$80
	sta     _laser_px
;
; laser_py = ((unsigned int)fallback_row << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 195
	dey
	lda     (c_sp),y
	sta     _laser_py+1
	lda     #$80
	sta     _laser_py
;
; laser_found = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 196
L0023:	lda     #$01
;
; laser_found = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 198
L001C:	sta     _laser_found
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 200
	ldy     #$0C
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_locate_exit (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_locate_exit: near

	.dbg	func, "sprite3d_locate_exit", "00", static, "_sprite3d_locate_exit"

.segment	"CODE"

;
; exit_px = ((unsigned int)maze_exit_col << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 211
	lda     _maze_exit_col
	sta     _exit_px+1
	lda     #$80
	sta     _exit_px
;
; exit_py = ((unsigned int)maze_exit_row << 8) | 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 212
	lda     _maze_exit_row
	sta     _exit_py+1
	lda     #$80
	sta     _exit_py
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 213
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_draw_targets (unsigned int px, unsigned int py, unsigned int angle)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_draw_targets: near

	.dbg	func, "sprite3d_draw_targets", "00", static, "_sprite3d_draw_targets"
	.dbg	sym, "px", "00", auto, 4
	.dbg	sym, "py", "00", auto, 2
	.dbg	sym, "angle", "00", auto, 0
	.dbg	sym, "i", "00", auto, -1
	.dbg	sym, "first_player", "00", auto, -2
	.dbg	sym, "used", "00", auto, -3

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 471
	jsr     pushax
;
; cand_count = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 476
	jsr     decsp3
	lda     #$00
	sta     _cand_count
;
; first_player = 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 477
	lda     #$01
	tay
	sta     (c_sp),y
;
; if (laser_found && project_object(px, py, angle, laser_px, laser_py)) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 479
	lda     _laser_found
	beq     L002B
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	lda     _laser_px
	ldx     _laser_px+1
	jsr     pushax
	lda     _laser_py
	ldx     _laser_py+1
	jsr     _project_object
	tax
	beq     L002B
;
; *(volatile unsigned char *)(PCOLR0 + 1) = LASER_COLOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 480
	lda     #$C8
	sta     $02C1
;
; draw_billboard(1, projected_x, projected_top, projected_height,
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 481
	lda     #$01
	jsr     pusha
	lda     _projected_x
	jsr     pusha
	lda     _projected_top
	jsr     pusha
	lda     _projected_height
	jsr     pusha
;
; laser_sprite, 16);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 482
	lda     #<(_laser_sprite)
	ldx     #>(_laser_sprite)
	jsr     pushax
	lda     #$10
	jsr     _draw_billboard
;
; first_player = 2;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 483
	lda     #$02
	ldy     #$01
	sta     (c_sp),y
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 484
	jmp     L002C
;
; *(volatile unsigned char *)(PCOLR0 + 1) = TARGET_COLOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 485
L002B:	lda     #$1E
	sta     $02C1
;
; cand_limit = (unsigned char)(PMG_PLAYERS - first_player);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 487
L002C:	lda     #$04
	sec
	ldy     #$01
	sbc     (c_sp),y
	sta     _cand_limit
;
; for (i = 0; i < target_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 489
	lda     #$00
	iny
L0023:	sta     (c_sp),y
	cmp     _target_count
	bcs     L002D
;
; if (!target_active[i]) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 490
	lda     (c_sp),y
	tay
	lda     _target_active,y
	beq     L0009
;
; if (project_object(px, py, angle, target_px[i], target_py[i]))
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 491
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0026
	inx
	clc
L0026:	adc     #<(_target_px)
	tay
	txa
	adc     #>(_target_px)
	tax
	tya
	jsr     pushw
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0027
	inx
	clc
L0027:	adc     #<(_target_py)
	tay
	txa
	adc     #>(_target_py)
	tax
	tya
	jsr     ldaxi
	jsr     _project_object
	tax
	beq     L0009
;
; add_candidate(projected_dist, projected_x, projected_top,
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 492
	lda     _projected_dist
	ldx     _projected_dist+1
	jsr     pushax
	lda     _projected_x
	jsr     pusha
	lda     _projected_top
	jsr     pusha
;
; projected_height);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 493
	lda     _projected_height
	jsr     _add_candidate
;
; for (i = 0; i < target_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 489
L0009:	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0023
;
; if (targets_left == 0 && maze_exit_found
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 495
L002D:	lda     _targets_left
	bne     L0034
;
; && project_object(px, py, angle, exit_px, exit_py))
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 496
	lda     _maze_exit_found
	beq     L0024
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	ldy     #$0A
	jsr     pushwysp
	lda     _exit_px
	ldx     _exit_px+1
	jsr     pushax
	lda     _exit_py
	ldx     _exit_py+1
	jsr     _project_object
	tax
	beq     L0031
;
; add_candidate(projected_dist, projected_x, projected_top, projected_height);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 497
	lda     _projected_dist
	ldx     _projected_dist+1
	jsr     pushax
	lda     _projected_x
	jsr     pusha
	lda     _projected_top
	jsr     pusha
	lda     _projected_height
	jsr     _add_candidate
;
; for (i = 0; i < cand_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 500
L0034:	lda     #$00
L0031:	ldy     #$02
L0024:	sta     (c_sp),y
	cmp     _cand_count
	bcs     L0013
;
; draw_billboard((unsigned char)(i + first_player), cand_x[i], cand_top[i],
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 501
	dey
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     _cand_x,y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     _cand_top,y
	jsr     pusha
;
; cand_height[i],
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 502
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     _cand_height,y
	jsr     pusha
;
; targets_left == 0 ? exit_sprite : target_sprite, 16);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 503
	lda     _targets_left
	bne     L0019
	lda     #<(_exit_sprite)
	ldx     #>(_exit_sprite)
	jmp     L001A
L0019:	lda     #<(_target_sprite)
	ldx     #>(_target_sprite)
L001A:	jsr     pushax
	lda     #$10
	jsr     _draw_billboard
;
; for (i = 0; i < cand_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 500
	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0024
;
; used = (unsigned char)(first_player + cand_count - 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 505
L0013:	dey
	lda     (c_sp),y
	clc
	adc     _cand_count
	sec
	sbc     #$01
	dey
	sta     (c_sp),y
;
; for (i = (unsigned char)(used + 1); i <= last_used; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 506
	clc
	adc     #$01
	ldy     #$02
L0025:	sta     (c_sp),y
	cmp     _last_used
	beq     L0033
	bcs     L001C
;
; clear_player(i);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 507
L0033:	lda     (c_sp),y
	jsr     _clear_player
;
; for (i = (unsigned char)(used + 1); i <= last_used; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 506
	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0025
;
; last_used = used;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 509
L001C:	ldy     #$00
	lda     (c_sp),y
	sta     _last_used
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 510
	ldy     #$09
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_draw_pursuer (unsigned int px, unsigned int py, unsigned int angle, unsigned int pursuer_x, unsigned int pursuer_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_draw_pursuer: near

	.dbg	func, "sprite3d_draw_pursuer", "00", static, "_sprite3d_draw_pursuer"
	.dbg	sym, "px", "00", auto, 8
	.dbg	sym, "py", "00", auto, 6
	.dbg	sym, "angle", "00", auto, 4
	.dbg	sym, "pursuer_x", "00", auto, 2
	.dbg	sym, "pursuer_y", "00", auto, 0
	.dbg	sym, "col", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2
	.dbg	sym, "target_col", "00", auto, -3
	.dbg	sym, "target_row", "00", auto, -4
	.dbg	sym, "dx", "00", auto, -5
	.dbg	sym, "dy", "00", auto, -6
	.dbg	sym, "step_x", "00", auto, -7
	.dbg	sym, "step_y", "00", auto, -8
	.dbg	sym, "error", "00", auto, -10
	.dbg	sym, "twice_error", "00", auto, -12

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 514
	jsr     pushax
;
; clear_player(0);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 526
	ldy     #$0C
	jsr     subysp
	lda     #$00
	jsr     _clear_player
;
; *(volatile unsigned char *)SIZEP0 = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 527
	lda     #$00
	sta     $D008
;
; if (!project_object(px, py, angle, pursuer_x, pursuer_y)) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 528
	ldy     #$17
	jsr     pushwysp
	ldy     #$17
	jsr     pushwysp
	ldy     #$17
	jsr     pushwysp
	ldy     #$17
	jsr     pushwysp
	ldy     #$15
	jsr     ldaxysp
	jsr     _project_object
	tax
	jeq     L0001
;
; col = (signed char)(px >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 530
	ldy     #$15
	lda     (c_sp),y
	cmp     #$80
	ldy     #$0B
	sta     (c_sp),y
;
; row = (signed char)(py >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 531
	ldy     #$13
	lda     (c_sp),y
	cmp     #$80
	ldy     #$0A
	sta     (c_sp),y
;
; target_col = (signed char)(pursuer_x >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 532
	ldy     #$0F
	lda     (c_sp),y
	cmp     #$80
	ldy     #$09
	sta     (c_sp),y
;
; target_row = (signed char)(pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 533
	ldy     #$0D
	lda     (c_sp),y
	cmp     #$80
	ldy     #$08
	sta     (c_sp),y
;
; dx = target_col > col ? target_col - col : col - target_col;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 534
	iny
	ldx     #$00
	lda     (c_sp),y
	bpl     L0007
	dex
L0007:	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (c_sp),y
	bpl     L0008
	dex
L0008:	jsr     tosicmp
	bmi     L0009
	beq     L0009
	ldy     #$09
	ldx     #$00
	lda     (c_sp),y
	bpl     L000A
	dex
L000A:	jsr     pushax
	ldy     #$0D
	jmp     L0052
L0009:	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L000D
	dex
L000D:	jsr     pushax
	ldy     #$0B
L0052:	ldx     #$00
	lda     (c_sp),y
	bpl     L000E
	dex
L000E:	jsr     tossubax
	cmp     #$80
	ldy     #$07
	sta     (c_sp),y
;
; dy = target_row > row ? row - target_row : target_row - row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 535
	iny
	ldx     #$00
	lda     (c_sp),y
	bpl     L0010
	dex
L0010:	jsr     pushax
	ldy     #$0C
	ldx     #$00
	lda     (c_sp),y
	bpl     L0011
	dex
L0011:	jsr     tosicmp
	bmi     L0012
	beq     L0012
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L0013
	dex
L0013:	jsr     pushax
	ldy     #$0A
	jmp     L0053
L0012:	ldy     #$08
	ldx     #$00
	lda     (c_sp),y
	bpl     L0016
	dex
L0016:	jsr     pushax
	ldy     #$0C
L0053:	ldx     #$00
	lda     (c_sp),y
	bpl     L0017
	dex
L0017:	jsr     tossubax
	cmp     #$80
	ldy     #$06
	sta     (c_sp),y
;
; step_x = col < target_col ? 1 : -1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 536
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L0019
	dex
L0019:	jsr     pushax
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L001A
	dex
L001A:	jsr     tosicmp
	bpl     L001B
	lda     #$01
	jmp     L0045
L001B:	lda     #$FF
L0045:	cmp     #$80
	ldy     #$05
	sta     (c_sp),y
;
; step_y = row < target_row ? 1 : -1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 537
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L001E
	dex
L001E:	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L001F
	dex
L001F:	jsr     tosicmp
	bpl     L0020
	lda     #$01
	jmp     L0046
L0020:	lda     #$FF
L0046:	cmp     #$80
	ldy     #$04
	sta     (c_sp),y
;
; error = dx + dy;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 538
	ldy     #$07
	ldx     #$00
	lda     (c_sp),y
	bpl     L0023
	dex
L0023:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	dey
	lda     (c_sp),y
	bpl     L0024
	dex
L0024:	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; while (col != target_col || row != target_row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 539
	jmp     L0042
;
; twice_error = error << 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 540
L0025:	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	jsr     stax0sp
;
; if (twice_error >= dy) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 541
	jsr     pushax
	ldy     #$08
	ldx     #$00
	lda     (c_sp),y
	bpl     L002F
	dex
L002F:	jsr     tosicmp
	bmi     L0033
;
; error += dy;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 542
	ldy     #$06
	ldx     #$00
	lda     (c_sp),y
	bpl     L0030
	dex
L0030:	ldy     #$02
	jsr     addeqysp
;
; col += step_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 543
	ldy     #$05
	lda     (c_sp),y
	cmp     #$80
	ldy     #$0B
	clc
	adc     (c_sp),y
	sta     (c_sp),y
;
; if (twice_error <= dx) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 545
L0033:	jsr     pushw0sp
	ldy     #$09
	ldx     #$00
	lda     (c_sp),y
	bpl     L0035
	dex
L0035:	jsr     tosicmp
	beq     L0044
	bpl     L0039
;
; error += dx;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 546
L0044:	ldy     #$07
	ldx     #$00
	lda     (c_sp),y
	bpl     L0036
	dex
L0036:	ldy     #$02
	jsr     addeqysp
;
; row += step_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 547
	ldy     #$04
	lda     (c_sp),y
	cmp     #$80
	ldy     #$0A
	clc
	adc     (c_sp),y
	sta     (c_sp),y
;
; if (col == target_col && row == target_row) break;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 549
L0039:	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L003B
	dex
L003B:	jsr     pushax
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L003C
	dex
L003C:	jsr     tosicmp
	bne     L003A
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L003E
	dex
L003E:	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L003F
	dex
L003F:	jsr     tosicmp
	beq     L0049
;
; if (maze_solid((unsigned char)col, (unsigned char)row)) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 550
L003A:	ldy     #$0B
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0B
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	bne     L0001
;
; while (col != target_col || row != target_row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 539
L0042:	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L0028
	dex
L0028:	jsr     pushax
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	bpl     L0029
	dex
L0029:	jsr     tosicmp
	jne     L0025
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L002B
	dex
L002B:	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	bpl     L002C
	dex
L002C:	jsr     tosicmp
	jne     L0025
;
; if (projected_height > 32) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 553
L0049:	lda     _projected_height
	cmp     #$21
	lda     #$00
	bcc     L004B
;
; projected_height = 32;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 554
	lda     #$20
	sta     _projected_height
;
; projected_top = (VIEW_ROWS - 32) >> 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 555
	lda     #$1E
	sta     _projected_top
;
; draw_billboard(0, projected_x, projected_top, projected_height,
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 557
	lda     #$00
L004B:	jsr     pusha
	lda     _projected_x
	jsr     pusha
	lda     _projected_top
	jsr     pusha
	lda     _projected_height
	jsr     pusha
;
; pursuer_sprite, 22);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 558
	lda     #<(_pursuer_sprite)
	ldx     #>(_pursuer_sprite)
	jsr     pushax
	lda     #$16
	jsr     _draw_billboard
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 559
L0001:	ldy     #$16
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_draw_decoy (unsigned char active, unsigned int px, unsigned int py, unsigned int angle, unsigned int decoy_x, unsigned int decoy_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_draw_decoy: near

	.dbg	func, "sprite3d_draw_decoy", "00", static, "_sprite3d_draw_decoy"
	.dbg	sym, "active", "00", auto, 10
	.dbg	sym, "px", "00", auto, 8
	.dbg	sym, "py", "00", auto, 6
	.dbg	sym, "angle", "00", auto, 4
	.dbg	sym, "decoy_x", "00", auto, 2
	.dbg	sym, "decoy_y", "00", auto, 0
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "i", "00", auto, -3
	.dbg	sym, "height", "00", auto, -4
	.dbg	sym, "size", "00", auto, -5
	.dbg	sym, "missile_width", "00", auto, -6
	.dbg	sym, "width", "00", auto, -7
	.dbg	sym, "acc", "00", auto, -9
	.dbg	sym, "step", "00", auto, -11
	.dbg	sym, "left", "00", auto, -13

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 419
	jsr     pushax
;
; clear_decoy();
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 430
	ldy     #$0D
	jsr     subysp
	jsr     _clear_decoy
;
; if (!active || !project_object(px, py, angle, decoy_x, decoy_y)) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 431
	ldy     #$17
	lda     (c_sp),y
	jeq     L0012
	iny
	jsr     pushwysp
	ldy     #$18
	jsr     pushwysp
	ldy     #$18
	jsr     pushwysp
	ldy     #$18
	jsr     pushwysp
	ldy     #$16
	jsr     ldaxysp
	jsr     _project_object
	tax
	jeq     L0012
;
; height = projected_height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 433
	lda     _projected_height
	ldy     #$09
	sta     (c_sp),y
;
; if (height > 32) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 434
	cmp     #$21
	bcc     L001D
;
; height = 32;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 435
	lda     #$20
	sta     (c_sp),y
;
; projected_top = (VIEW_ROWS - 32) >> 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 436
	lda     #$1E
	sta     _projected_top
;
; if (height >= 24) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 438
L001D:	lda     (c_sp),y
	cmp     #$18
	lda     #$00
	bcc     L001F
;
; size = 0x55;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 439
	lda     #$55
	dey
	sta     (c_sp),y
;
; missile_width = 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 440
	lda     #$04
	dey
	sta     (c_sp),y
;
; width = 16;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 441
	lda     #$10
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 442
	jmp     L0021
;
; size = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 443
L001F:	dey
	sta     (c_sp),y
;
; missile_width = 2;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 444
	lda     #$02
	dey
	sta     (c_sp),y
;
; width = 8;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 445
	lda     #$08
L0021:	dey
	sta     (c_sp),y
;
; left = (int)projected_x - (width >> 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 448
	lda     _projected_x
	jsr     pusha0
	ldy     #$08
	lda     (c_sp),y
	lsr     a
	jsr     tossuba0
	jsr     stax0sp
;
; if (left < VIEW_LEFT_PX) left = VIEW_LEFT_PX;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 449
	cmp     #$14
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	bpl     L0008
	ldx     #$00
	lda     #$14
	jsr     stax0sp
;
; if (left + width > VIEW_RIGHT_PX + 1)
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 450
L0008:	ldx     #$00
	ldy     #$06
	lda     (c_sp),y
	clc
	ldy     #$00
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	cmp     #$A1
	txa
	sbc     #$00
	bvs     L000B
	eor     #$80
L000B:	bpl     L000A
;
; left = VIEW_RIGHT_PX + 1 - width;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 451
	lda     #$A0
	sec
	ldy     #$06
	sbc     (c_sp),y
	ldx     #$00
	bcs     L0016
	dex
L0016:	jsr     stax0sp
;
; dest = pmg_ram + PMG_MISSILE_OFFSET + PMG_TOP_OFFSET + projected_top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 453
L000A:	lda     #<(_pmg_ram+402)
	ldx     #>(_pmg_ram+402)
	clc
	adc     _projected_top
	bcc     L000C
	inx
L000C:	ldy     #$0B
	jsr     staxysp
;
; step = ((unsigned int)8 << 8) / height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 454
	ldx     #$08
	lda     #$00
	jsr     pushax
	ldy     #$0B
	lda     (c_sp),y
	jsr     tosudiva0
	ldy     #$02
	jsr     staxysp
;
; acc = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 455
	ldx     #$00
	txa
	ldy     #$04
	jsr     staxysp
;
; for (i = 0; i < height; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 456
	ldy     #$0A
L0018:	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	dey
	cmp     (c_sp),y
	bcs     L0020
;
; dest[i] = decoy_sprite[acc >> 8];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 457
	iny
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	sta     sreg
	txa
	iny
	adc     (c_sp),y
	sta     sreg+1
	ldy     #$05
	lda     (c_sp),y
	sta     ptr1
	clc
	lda     #>(_decoy_sprite)
	sta     ptr1+1
	ldy     #<(_decoy_sprite)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; acc += step;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 458
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     addeqysp
;
; for (i = 0; i < height; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 456
	ldy     #$0A
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0018
;
; decoy_clear_top = (unsigned char)(PMG_TOP_OFFSET + projected_top);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 460
L0020:	lda     _projected_top
	ldy     #$12
	jsr     incaxy
	sta     _decoy_clear_top
;
; decoy_clear_height = height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 461
	ldy     #$09
	lda     (c_sp),y
	sta     _decoy_clear_height
;
; *(volatile unsigned char *)0xD00C = size;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 463
	dey
	lda     (c_sp),y
	sta     $D00C
;
; for (i = 0; i < 4; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 464
	lda     #$00
	ldy     #$0A
L0019:	sta     (c_sp),y
	cmp     #$04
	bcs     L0012
;
; *(volatile unsigned char *)(0xD004 + i) =
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 465
	ldx     #$D0
	lda     #$04
	clc
	adc     (c_sp),y
	bcc     L0015
	inx
;
; (unsigned char)(48 + left + i * missile_width);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 466
L0015:	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$30
	jsr     incaxy
	jsr     pushax
	ldy     #$0E
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$0D
	lda     (c_sp),y
	jsr     tosumula0
	jsr     tosaddax
	ldy     #$00
	jsr     staspidx
;
; for (i = 0; i < 4; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 464
	ldy     #$0A
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0019
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 468
L0012:	ldy     #$18
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sprite3d_collect (unsigned int px, unsigned int py)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_collect: near

	.dbg	func, "sprite3d_collect", "00", static, "_sprite3d_collect"
	.dbg	sym, "px", "00", auto, 2
	.dbg	sym, "py", "00", auto, 0
	.dbg	sym, "i", "00", auto, -1
	.dbg	sym, "taken", "00", auto, -2
	.dbg	sym, "dx", "00", auto, -4
	.dbg	sym, "dy", "00", auto, -6

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 232
	jsr     pushax
;
; taken = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 238
	jsr     decsp6
	lda     #$00
	ldy     #$04
	sta     (c_sp),y
;
; for (i = 0; i < target_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 239
	iny
L0011:	sta     (c_sp),y
	cmp     _target_count
	jcs     L0003
;
; if (!target_active[i]) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 240
	lda     (c_sp),y
	tay
	lda     _target_active,y
	jeq     L0004
;
; dx = (int)target_px[i] - (int)px;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 241
	ldy     #$05
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0012
	inx
	clc
L0012:	adc     #<(_target_px)
	tay
	txa
	adc     #>(_target_px)
	tax
	tya
	jsr     ldaxi
	sec
	ldy     #$08
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; if (dx < 0) dx = -dx;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 242
	cpx     #$80
	bcc     L0008
	ldy     #$03
	jsr     ldaxysp
	jsr     negax
	ldy     #$02
	jsr     staxysp
;
; if (dx >= COLLECT_RADIUS) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 243
L0008:	ldy     #$03
	jsr     ldaxysp
	cmp     #$A0
	txa
	sbc     #$00
	bvs     L000A
	eor     #$80
L000A:	bmi     L0004
;
; dy = (int)target_py[i] - (int)py;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 244
	ldy     #$05
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0013
	inx
	clc
L0013:	adc     #<(_target_py)
	tay
	txa
	adc     #>(_target_py)
	tax
	tya
	jsr     ldaxi
	sec
	ldy     #$06
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     stax0sp
;
; if (dy < 0) dy = -dy;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 245
	cpx     #$80
	bcc     L000B
	jsr     ldax0sp
	jsr     negax
	jsr     stax0sp
;
; if (dy >= COLLECT_RADIUS) continue;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 246
L000B:	jsr     ldax0sp
	cmp     #$A0
	txa
	sbc     #$00
	bvs     L000D
	eor     #$80
L000D:	bmi     L0004
;
; target_active[i] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 247
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _target_active,y
;
; --targets_left;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 248
	dec     _targets_left
;
; ++taken;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 249
	ldy     #$04
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; for (i = 0; i < target_count; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 239
L0004:	ldy     #$05
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0011
;
; return taken;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 251
L0003:	dey
	ldx     #$00
	lda     (c_sp),y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 252
	ldy     #$0A
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sprite3d_hit_laser (unsigned int px, unsigned int py)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_hit_laser: near

	.dbg	func, "sprite3d_hit_laser", "00", static, "_sprite3d_hit_laser"
	.dbg	sym, "px", "00", auto, 2
	.dbg	sym, "py", "00", auto, 0
	.dbg	sym, "dx", "00", auto, -2
	.dbg	sym, "dy", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 255
	jsr     pushax
;
; if (!laser_found) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 259
	jsr     decsp4
	lda     _laser_found
	beq     L0008
;
; dx = (int)laser_px - (int)px;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 260
	lda     _laser_px
	sec
	ldy     #$06
	sbc     (c_sp),y
	pha
	lda     _laser_px+1
	iny
	sbc     (c_sp),y
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; if (dx < 0) dx = -dx;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 261
	cpx     #$80
	bcc     L0003
	ldy     #$03
	jsr     ldaxysp
	jsr     negax
	ldy     #$02
	jsr     staxysp
;
; if (dx >= COLLECT_RADIUS) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 262
L0003:	ldy     #$03
	jsr     ldaxysp
	cmp     #$A0
	txa
	sbc     #$00
	bvs     L0005
	eor     #$80
L0005:	bpl     L0004
	ldx     #$00
	txa
	jmp     incsp8
;
; dy = (int)laser_py - (int)py;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 263
L0004:	lda     _laser_py
	sec
	ldy     #$04
	sbc     (c_sp),y
	pha
	lda     _laser_py+1
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     stax0sp
;
; if (dy < 0) dy = -dy;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 264
	cpx     #$80
	bcc     L0006
	jsr     ldax0sp
	jsr     negax
	jsr     stax0sp
;
; return dy < COLLECT_RADIUS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 265
L0006:	jsr     ldax0sp
	cmp     #$A0
	txa
	sbc     #$00
	bvc     L0007
	eor     #$80
L0007:	asl     a
	lda     #$00
	rol     a
L0008:	ldx     #$00
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 266
	jmp     incsp8

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sprite3d_targets_left (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_targets_left: near

	.dbg	func, "sprite3d_targets_left", "00", static, "_sprite3d_targets_left"

.segment	"CODE"

;
; return targets_left;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 204
	ldx     #$00
	lda     _targets_left
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 205
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ sprite3d_clear_all (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_clear_all: near

	.dbg	func, "sprite3d_clear_all", "00", static, "_sprite3d_clear_all"
	.dbg	sym, "player", "00", auto, -1

.segment	"CODE"

;
; for (player = 0; player < PMG_PLAYERS; ++player) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 295
	jsr     decsp1
	lda     #$00
	tay
L0006:	sta     (c_sp),y
	cmp     #$04
	bcs     L0003
;
; clear_player(player);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 296
	lda     (c_sp),y
	jsr     _clear_player
;
; for (player = 0; player < PMG_PLAYERS; ++player) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 295
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0006
;
; clear_decoy();
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 298
L0003:	jsr     _clear_decoy
;
; last_used = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 299
	lda     #$00
	sta     _last_used
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 300
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sprite3d_reached_exit (unsigned int px, unsigned int py)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sprite3d_reached_exit: near

	.dbg	func, "sprite3d_reached_exit", "00", static, "_sprite3d_reached_exit"
	.dbg	sym, "px", "00", auto, 2
	.dbg	sym, "py", "00", auto, 0
	.dbg	sym, "dx", "00", auto, -2
	.dbg	sym, "dy", "00", auto, -4

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 216
	jsr     pushax
;
; if (!maze_exit_found || targets_left != 0) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 220
	jsr     decsp4
	lda     _maze_exit_found
	beq     L000A
	lda     _targets_left
	beq     L0002
L000A:	ldx     #$00
	txa
	jmp     incsp8
;
; dx = (int)exit_px - (int)px;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 221
L0002:	lda     _exit_px
	sec
	ldy     #$06
	sbc     (c_sp),y
	pha
	lda     _exit_px+1
	iny
	sbc     (c_sp),y
	tax
	pla
	ldy     #$02
	jsr     staxysp
;
; if (dx < 0) dx = -dx;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 222
	cpx     #$80
	bcc     L0005
	ldy     #$03
	jsr     ldaxysp
	jsr     negax
	ldy     #$02
	jsr     staxysp
;
; if (dx >= COLLECT_RADIUS) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 223
L0005:	ldy     #$03
	jsr     ldaxysp
	cmp     #$A0
	txa
	sbc     #$00
	bvs     L0007
	eor     #$80
L0007:	bpl     L0006
	ldx     #$00
	txa
	jmp     incsp8
;
; dy = (int)exit_py - (int)py;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 224
L0006:	lda     _exit_py
	sec
	ldy     #$04
	sbc     (c_sp),y
	pha
	lda     _exit_py+1
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     stax0sp
;
; if (dy < 0) dy = -dy;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 225
	cpx     #$80
	bcc     L0008
	jsr     ldax0sp
	jsr     negax
	jsr     stax0sp
;
; return dy < COLLECT_RADIUS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 226
L0008:	jsr     ldax0sp
	cmp     #$A0
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	asl     a
	lda     #$00
	rol     a
	ldx     #$00
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 227
	jmp     incsp8

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ draw_billboard (unsigned char player, unsigned char sx, unsigned char top, unsigned char height, const unsigned char *sprite, unsigned char sprite_rows)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_billboard: near

	.dbg	func, "draw_billboard", "00", static, "_draw_billboard"
	.dbg	sym, "player", "00", auto, 6
	.dbg	sym, "sx", "00", auto, 5
	.dbg	sym, "top", "00", auto, 4
	.dbg	sym, "height", "00", auto, 3
	.dbg	sym, "sprite", "00", auto, 1
	.dbg	sym, "sprite_rows", "00", auto, 0
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "i", "00", auto, -3
	.dbg	sym, "size", "00", auto, -4
	.dbg	sym, "width", "00", auto, -5
	.dbg	sym, "acc", "00", auto, -7
	.dbg	sym, "step", "00", auto, -9
	.dbg	sym, "left", "00", auto, -11

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 305
	jsr     pusha
;
; if (height >= 48) { size = 3; width = 32; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 315
	ldy     #$0B
	jsr     subysp
	ldy     #$0E
	lda     (c_sp),y
	cmp     #$30
	bcc     L0016
	lda     #$03
	ldy     #$07
	sta     (c_sp),y
	lda     #$20
;
; else if (height >= 24) { size = 1; width = 16; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 316
	jmp     L0019
L0016:	lda     (c_sp),y
	cmp     #$18
	lda     #$00
	bcc     L0018
	lda     #$01
	ldy     #$07
	sta     (c_sp),y
	lda     #$10
;
; else { size = 0; width = 8; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 317
	jmp     L0019
L0018:	ldy     #$07
	sta     (c_sp),y
	lda     #$08
L0019:	dey
	sta     (c_sp),y
;
; left = (int)sx - (width >> 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 319
	ldy     #$10
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$08
	lda     (c_sp),y
	lsr     a
	jsr     tossuba0
	jsr     stax0sp
;
; if (left < VIEW_LEFT_PX) left = VIEW_LEFT_PX;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 320
	cmp     #$14
	txa
	sbc     #$00
	bvc     L0007
	eor     #$80
L0007:	bpl     L0006
	ldx     #$00
	lda     #$14
	jsr     stax0sp
;
; if (left + width > VIEW_RIGHT_PX + 1)
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 321
L0006:	ldx     #$00
	ldy     #$06
	lda     (c_sp),y
	clc
	ldy     #$00
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	cmp     #$A1
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
;
; left = VIEW_RIGHT_PX + 1 - width;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 322
	lda     #$A0
	sec
	ldy     #$06
	sbc     (c_sp),y
	ldx     #$00
	bcs     L0012
	dex
L0012:	jsr     stax0sp
;
; clear_player(player);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 324
L0008:	ldy     #$11
	lda     (c_sp),y
	jsr     _clear_player
;
; dest = pmg_ram + PMG_PLAYER0_OFFSET + ((unsigned int)player << 7);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 325
	ldy     #$11
	ldx     #$00
	lda     (c_sp),y
	jsr     shlax7
	clc
	adc     #<(_pmg_ram+512)
	tay
	txa
	adc     #>(_pmg_ram+512)
	tax
	tya
	ldy     #$09
	jsr     staxysp
;
; step = ((unsigned int)sprite_rows << 8) / height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 327
	ldy     #$0B
	lda     (c_sp),y
	tax
	lda     #$00
	jsr     pushax
	ldy     #$10
	lda     (c_sp),y
	jsr     tosudiva0
	ldy     #$02
	jsr     staxysp
;
; acc = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 328
	ldx     #$00
	txa
	ldy     #$04
	jsr     staxysp
;
; dest += PMG_TOP_OFFSET + top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 329
	ldy     #$0F
	lda     (c_sp),y
	ldy     #$12
	jsr     incaxy
	ldy     #$09
	jsr     addeqysp
;
; for (i = 0; i < height; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 330
	lda     #$00
	ldy     #$08
L0014:	sta     (c_sp),y
	ldy     #$0E
	cmp     (c_sp),y
	bcs     L000B
;
; dest[i] = sprite[acc >> 8];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 331
	ldy     #$08
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	sta     sreg
	lda     #$00
	iny
	adc     (c_sp),y
	sta     sreg+1
	ldy     #$0D
	jsr     ldptr1ysp
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; acc += step;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 332
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     addeqysp
;
; for (i = 0; i < height; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 330
	ldy     #$08
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0014
;
; player_clear_top[player] = (unsigned char)(PMG_TOP_OFFSET + top);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 334
L000B:	lda     #<(_player_clear_top)
	ldx     #>(_player_clear_top)
	ldy     #$11
	clc
	adc     (c_sp),y
	bcc     L000E
	inx
L000E:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$0F
	lda     (c_sp),y
	ldy     #$12
	jsr     incaxy
	ldy     #$00
	sta     (ptr1),y
;
; player_clear_height[player] = height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 335
	ldy     #$11
	lda     (c_sp),y
	tax
	ldy     #$0E
	lda     (c_sp),y
	sta     _player_clear_height,x
;
; *(volatile unsigned char *)(SIZEP0 + player) = size;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 337
	ldy     #$11
	lda     (c_sp),y
	tax
	ldy     #$07
	lda     (c_sp),y
	sta     $D008,x
;
; *(volatile unsigned char *)(HPOSP0 + player) =
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 338
	ldx     #$D0
	ldy     #$11
	clc
	lda     (c_sp),y
	bcc     L0011
	inx
;
; (unsigned char)(48 + left);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 339
L0011:	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$30
	jsr     incaxy
	ldy     #$00
	sta     (ptr1),y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 340
	ldy     #$12
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ clear_player (unsigned char player)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_player: near

	.dbg	func, "clear_player", "00", static, "_clear_player"
	.dbg	sym, "player", "00", auto, 0
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "i", "00", auto, -3

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 269
	jsr     pusha
;
; dest = pmg_ram + PMG_PLAYER0_OFFSET + ((unsigned int)player << 7)
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 273
	jsr     decsp3
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     shlax7
;
; + player_clear_top[player];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 274
	clc
	adc     #<(_pmg_ram+512)
	sta     ptr1
	txa
	adc     #>(_pmg_ram+512)
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     _player_clear_top,y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0009
	inx
L0009:	ldy     #$01
	jsr     staxysp
;
; for (i = 0; i < player_clear_height[player]; ++i) dest[i] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 275
	lda     #$00
	tay
L000A:	sta     (c_sp),y
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     _player_clear_height,y
	ldy     #$00
	cmp     (c_sp),y
	bcc     L0004
	beq     L0004
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000A
;
; player_clear_height[player] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 276
L0004:	ldy     #$03
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _player_clear_height,y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 277
	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ clear_decoy (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_decoy: near

	.dbg	func, "clear_decoy", "00", static, "_clear_decoy"
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "i", "00", auto, -3

.segment	"CODE"

;
; dest = pmg_ram + PMG_MISSILE_OFFSET + decoy_clear_top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 284
	jsr     decsp3
	lda     #<(_pmg_ram+384)
	ldx     #>(_pmg_ram+384)
	clc
	adc     _decoy_clear_top
	bcc     L0002
	inx
L0002:	ldy     #$01
	jsr     staxysp
;
; for (i = 0; i < decoy_clear_height; ++i) dest[i] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 285
	lda     #$00
	tay
L0007:	sta     (c_sp),y
	cmp     _decoy_clear_height
	bcs     L0008
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0007
;
; decoy_clear_height = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 286
L0008:	sty     _decoy_clear_height
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 287
	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ add_candidate (unsigned int dist, unsigned char sx, unsigned char top, unsigned char height)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_candidate: near

	.dbg	func, "add_candidate", "00", static, "_add_candidate"
	.dbg	sym, "dist", "00", auto, 3
	.dbg	sym, "sx", "00", auto, 2
	.dbg	sym, "top", "00", auto, 1
	.dbg	sym, "height", "00", auto, 0
	.dbg	sym, "slot", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 344
	jsr     pusha
;
; if (cand_count == cand_limit && dist >= cand_dist[cand_limit - 1]) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 347
	jsr     decsp1
	lda     _cand_count
	cmp     _cand_limit
	bne     L001C
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	lda     _cand_limit
	jsr     decax1
	jsr     aslax1
	clc
	adc     #<(_cand_dist)
	tay
	txa
	adc     #>(_cand_dist)
	tax
	tya
	jsr     ldaxi
	jsr     tosicmp
	jcs     L0014
;
; slot = cand_count < cand_limit ? cand_count : (unsigned char)(cand_limit - 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 349
L001C:	lda     _cand_count
	cmp     _cand_limit
	bcs     L001D
	jmp     L001E
L001D:	lda     _cand_limit
	sec
	sbc     #$01
L001E:	ldy     #$00
;
; while (slot > 0 && cand_dist[slot - 1] > dist) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 350
	jmp     L0018
;
; cand_dist[slot] = cand_dist[slot - 1];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 351
L0008:	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L0019
	inx
	clc
L0019:	adc     #<(_cand_dist)
	sta     sreg
	txa
	adc     #>(_cand_dist)
	sta     sreg+1
	ldx     #$00
	lda     (c_sp,x)
	jsr     decax1
	jsr     aslax1
	clc
	adc     #<(_cand_dist)
	tay
	txa
	adc     #>(_cand_dist)
	tax
	tya
	jsr     ldaxi
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
;
; cand_x[slot] = cand_x[slot - 1];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 352
	lda     #<(_cand_x)
	ldx     #>(_cand_x)
	dey
	clc
	adc     (c_sp),y
	bcc     L000E
	inx
L000E:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	sta     ptr1
	txa
	clc
	adc     #>(_cand_x)
	sta     ptr1+1
	ldy     #<(_cand_x)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; cand_top[slot] = cand_top[slot - 1];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 353
	lda     #<(_cand_top)
	ldx     #>(_cand_top)
	clc
	adc     (c_sp),y
	bcc     L000F
	inx
L000F:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	sta     ptr1
	txa
	clc
	adc     #>(_cand_top)
	sta     ptr1+1
	ldy     #<(_cand_top)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; cand_height[slot] = cand_height[slot - 1];
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 354
	lda     #<(_cand_height)
	ldx     #>(_cand_height)
	clc
	adc     (c_sp),y
	bcc     L0010
	inx
L0010:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	sta     ptr1
	txa
	clc
	adc     #>(_cand_height)
	sta     ptr1+1
	ldy     #<(_cand_height)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; --slot;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 355
	lda     (c_sp),y
	sec
	sbc     #$01
L0018:	sta     (c_sp),y
;
; while (slot > 0 && cand_dist[slot - 1] > dist) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 350
	lda     (c_sp),y
	beq     L0021
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	jsr     aslax1
	clc
	adc     #<(_cand_dist)
	tay
	txa
	adc     #>(_cand_dist)
	tax
	tya
	jsr     ldaxi
	sec
	ldy     #$04
	sbc     (c_sp),y
	sta     tmp1
	txa
	iny
	sbc     (c_sp),y
	ora     tmp1
	beq     L0021
	jcs     L0008
;
; cand_dist[slot] = dist;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 357
L0021:	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L001A
	inx
	clc
L001A:	adc     #<(_cand_dist)
	sta     ptr1
	txa
	adc     #>(_cand_dist)
	sta     ptr1+1
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
;
; cand_x[slot] = sx;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 358
	dey
	lda     (c_sp),y
	tax
	ldy     #$03
	lda     (c_sp),y
	sta     _cand_x,x
;
; cand_top[slot] = top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 359
	ldy     #$00
	lda     (c_sp),y
	tax
	ldy     #$02
	lda     (c_sp),y
	sta     _cand_top,x
;
; cand_height[slot] = height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 360
	ldy     #$00
	lda     (c_sp),y
	tax
	iny
	lda     (c_sp),y
	sta     _cand_height,x
;
; if (cand_count < cand_limit) ++cand_count;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 361
	lda     _cand_count
	cmp     _cand_limit
	bcs     L0014
	inc     _cand_count
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 362
L0014:	jmp     incsp6

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ project_object (unsigned int px, unsigned int py, unsigned int angle, unsigned int object_x, unsigned int object_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_project_object: near

	.dbg	func, "project_object", "00", static, "_project_object"
	.dbg	sym, "px", "00", auto, 8
	.dbg	sym, "py", "00", auto, 6
	.dbg	sym, "angle", "00", auto, 4
	.dbg	sym, "object_x", "00", auto, 2
	.dbg	sym, "object_y", "00", auto, 0
	.dbg	sym, "idx", "00", auto, -1
	.dbg	sym, "column", "00", auto, -2
	.dbg	sym, "height", "00", auto, -3
	.dbg	sym, "top", "00", auto, -4
	.dbg	sym, "cos_h", "00", auto, -6
	.dbg	sym, "sin_h", "00", auto, -8
	.dbg	sym, "dx", "00", auto, -10
	.dbg	sym, "dy", "00", auto, -12
	.dbg	sym, "forward", "00", auto, -14
	.dbg	sym, "right", "00", auto, -16
	.dbg	sym, "limit", "00", auto, -18
	.dbg	sym, "screen_x", "00", auto, -20

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 367
	jsr     pushax
;
; idx = (unsigned char)(angle >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 381
	ldy     #$14
	jsr     subysp
	ldy     #$19
	lda     (c_sp),y
	ldy     #$13
	sta     (c_sp),y
;
; cos_h = sin3d[(unsigned char)(idx + 64)] >> 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 382
	ldx     #$00
	lda     (c_sp),y
	ldy     #$40
	jsr     incaxy
	ldx     #$00
	asl     a
	bcc     L001E
	inx
	clc
L001E:	adc     #<(_sin3d)
	tay
	txa
	adc     #>(_sin3d)
	tax
	tya
	jsr     ldaxi
	jsr     asrax1
	ldy     #$0E
	jsr     staxysp
;
; sin_h = sin3d[idx] >> 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 383
	ldy     #$13
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L001F
	inx
	clc
L001F:	adc     #<(_sin3d)
	tay
	txa
	adc     #>(_sin3d)
	tax
	tya
	jsr     ldaxi
	jsr     asrax1
	ldy     #$0C
	jsr     staxysp
;
; dx = ((int)object_x - (int)px) >> 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 384
	ldy     #$17
	jsr     ldaxysp
	sec
	ldy     #$1C
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     asrax4
	ldy     #$0A
	jsr     staxysp
;
; dy = ((int)object_y - (int)py) >> 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 385
	ldy     #$15
	jsr     ldaxysp
	sec
	ldy     #$1A
	sbc     (c_sp),y
	pha
	txa
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     asrax4
	ldy     #$08
	jsr     staxysp
;
; if (dx > RANGE_44 || dx < -RANGE_44 || dy > RANGE_44 || dy < -RANGE_44)
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 386
	ldy     #$0B
	jsr     ldaxysp
	cmp     #$C1
	txa
	sbc     #$00
	bvs     L0003
	eor     #$80
L0003:	bmi     L0022
	ldy     #$0B
	jsr     ldaxysp
	cmp     #$40
	txa
	sbc     #$FF
	bvc     L0005
	eor     #$80
L0005:	bmi     L0022
	ldy     #$09
	jsr     ldaxysp
	cmp     #$C1
	txa
	sbc     #$00
	bvs     L0006
	eor     #$80
L0006:	bmi     L0022
	ldy     #$09
	jsr     ldaxysp
	cmp     #$40
	txa
	sbc     #$FF
	bvc     L0007
	eor     #$80
L0007:	bpl     L0002
;
; return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 387
L0022:	ldx     #$00
	txa
	jmp     L0001
;
; forward = ((dx * cos_h) >> 7) + ((dy * sin_h) >> 7);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 389
L0002:	ldy     #$0D
	jsr     pushwysp
	ldy     #$11
	jsr     ldaxysp
	jsr     tosmulax
	jsr     asrax7
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$11
	jsr     ldaxysp
	jsr     tosmulax
	jsr     asrax7
	jsr     tosaddax
	ldy     #$06
	jsr     staxysp
;
; if (forward <= 0) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 394
	cmp     #$01
	txa
	sbc     #$00
	bvc     L000A
	eor     #$80
L000A:	bpl     L0009
	ldx     #$00
	txa
	jmp     L0001
;
; if (forward <= 8) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 395
L0009:	ldy     #$07
	jsr     ldaxysp
	cmp     #$09
	txa
	sbc     #$00
	bvc     L000C
	eor     #$80
L000C:	bpl     L000B
	ldx     #$00
	txa
	jmp     L0001
;
; right = ((-dx * sin_h) >> 7) + ((dy * cos_h) >> 7);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 396
L000B:	ldy     #$0B
	jsr     ldaxysp
	jsr     negax
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosmulax
	jsr     asrax7
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$13
	jsr     ldaxysp
	jsr     tosmulax
	jsr     asrax7
	jsr     tosaddax
	ldy     #$04
	jsr     staxysp
;
; limit = (forward * 5) >> 3;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 397
	ldy     #$07
	jsr     ldaxysp
	jsr     mulax5
	jsr     asrax3
	ldy     #$02
	jsr     staxysp
;
; if (right > limit || right < -limit) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 398
	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     tosicmp
	beq     L0021
	bpl     L000E
L0021:	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     negax
	jsr     tosicmp
	bpl     L000D
L000E:	ldx     #$00
	txa
	jmp     L0001
;
; screen_x = VIEW_CENTER_PX + ((right * PROJ_X) / forward);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 400
L000D:	ldy     #$07
	jsr     pushwysp
	lda     #$79
	jsr     tosmula0
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosdivax
	ldy     #$5A
	jsr     incaxy
	jsr     stax0sp
;
; if (screen_x < VIEW_LEFT_PX || screen_x > VIEW_RIGHT_PX) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 401
	cmp     #$14
	txa
	sbc     #$00
	bvc     L0011
	eor     #$80
L0011:	bmi     L0023
	jsr     ldax0sp
	cmp     #$A0
	txa
	sbc     #$00
	bvs     L0013
	eor     #$80
L0013:	bpl     L0010
L0023:	ldx     #$00
	txa
	jmp     L0001
;
; column = (unsigned char)((screen_x - VIEW_LEFT_PX) >> 3);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 402
L0010:	jsr     ldax0sp
	ldy     #$14
	jsr     decaxy
	jsr     asrax3
	ldy     #$12
	sta     (c_sp),y
;
; if (column >= VIEW_COLS) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 403
	cmp     #$12
	bcc     L0015
	ldx     #$00
	txa
	jmp     L0001
;
; projected_dist = (unsigned int)forward << 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 405
L0015:	ldy     #$07
	jsr     ldaxysp
	jsr     shlax4
	sta     _projected_dist
	stx     _projected_dist+1
;
; if (projected_dist > col_dist[column]) return 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 406
	jsr     pushax
	ldy     #$14
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0020
	inx
	clc
L0020:	adc     #<(_col_dist)
	tay
	txa
	adc     #>(_col_dist)
	tax
	tya
	jsr     ldaxi
	jsr     tosicmp
	bcc     L0016
	beq     L0016
	ldx     #$00
	txa
	jmp     L0001
;
; height = view3d_wall_height(projected_dist);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 407
L0016:	lda     _projected_dist
	ldx     _projected_dist+1
	jsr     _view3d_wall_height
	ldy     #$11
	sta     (c_sp),y
;
; top = height >= VIEW_ROWS ? 0 : (unsigned char)((VIEW_ROWS - height) >> 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 408
	cmp     #$5C
	bcc     L0024
	lda     #$00
	jmp     L0025
L0024:	lda     #$5C
	sec
	sbc     (c_sp),y
	ldx     #$00
	bcs     L001D
	dex
L001D:	jsr     asrax1
L0025:	dey
	sta     (c_sp),y
;
; if (height > VIEW_ROWS) height = VIEW_ROWS;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 409
	iny
	lda     (c_sp),y
	cmp     #$5D
	bcc     L0019
	lda     #$5C
	sta     (c_sp),y
;
; projected_x = (unsigned char)screen_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 410
L0019:	ldy     #$00
	lda     (c_sp),y
	sta     _projected_x
;
; projected_top = top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 411
	ldy     #$10
	lda     (c_sp),y
	sta     _projected_top
;
; projected_height = height;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 412
	iny
	lda     (c_sp),y
	sta     _projected_height
;
; return 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 413
	ldx     #$00
	lda     #$01
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\sprite3d.c", 414
L0001:	ldy     #$1E
	jmp     addysp

	.dbg	line
.endproc

