;
; File generated by cc65 v 2.19 - Git 547d923
;
	.fopt		compiler,"cc65 v 2.19 - Git 547d923"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "C:\Users\Alex\Chased3D\view3d.c", 14779, 1788211377
	.dbg		file, "C:\tools\cc65\include/atari.h", 22152, 1786840064
	.dbg		file, "C:\tools\cc65\include/_atarios.h", 40084, 1786840064
	.dbg		file, "C:\tools\cc65\include/_gtia.h", 13839, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pbi.h", 3143, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pokey.h", 11376, 1786840064
	.dbg		file, "C:\tools\cc65\include/_pia.h", 3044, 1786840064
	.dbg		file, "C:\tools\cc65\include/_antic.h", 11827, 1786840064
	.dbg		file, "C:\Users\Alex\Chased3D/maze.h", 550, 1787868964
	.dbg		file, "C:\Users\Alex\Chased3D/trig3d.h", 333, 1787781160
	.dbg		file, "C:\Users\Alex\Chased3D/view3d.h", 1299, 1788211140
	.dbg		file, "C:\Users\Alex\Chased3D/build_number.h", 136, 1788211381
	.dbg		sym, "ray_offset", "00", extern, "_ray_offset"
	.dbg		sym, "cos_rel", "00", extern, "_cos_rel"
	.dbg		sym, "col3d_x", "00", extern, "_col3d_x"
	.dbg		sym, "col3d_row", "00", extern, "_col3d_row"
	.dbg		sym, "col3d_end", "00", extern, "_col3d_end"
	.dbg		sym, "col3d_color", "00", extern, "_col3d_color"
	.dbg		sym, "dda_side_x", "00", extern, "_dda_side_x"
	.dbg		sym, "dda_side_y", "00", extern, "_dda_side_y"
	.dbg		sym, "dda_delta_x", "00", extern, "_dda_delta_x"
	.dbg		sym, "dda_delta_y", "00", extern, "_dda_delta_y"
	.dbg		sym, "dda_side", "00", extern, "_dda_side"
	.dbg		sym, "dda_hit", "00", extern, "_dda_hit"
	.dbg		sym, "ray_setup_angle", "00", extern, "_ray_setup_angle"
	.dbg		sym, "ray_setup_px", "00", extern, "_ray_setup_px"
	.dbg		sym, "ray_setup_py", "00", extern, "_ray_setup_py"
	.import		_maze_solid
	.import		_ray_offset
	.import		_cos_rel
	.export		_view3d_init
	.export		_view3d_render
	.export		_view3d_floor_motion
	.export		_view3d_wall_height
	.export		_minimap_build
	.export		_minimap_show
	.export		_minimap_update
	.export		_hud_set_fps
	.export		_hud_set_targets
	.export		_hud_set_game
	.export		_hud_set_decoy
	.export		_col_dist
	.export		_view_buffer
	.import		_col3d_x
	.import		_col3d_row
	.import		_col3d_end
	.import		_col3d_color
	.import		_col3d_fill_down
	.import		_col3d_fill_up
	.import		_col3d_fill_span
	.import		_dda_side_x
	.import		_dda_side_y
	.import		_dda_delta_x
	.import		_dda_delta_y
	.import		_dda_side
	.import		_dda_hit
	.import		_ray_setup_angle
	.import		_ray_setup_px
	.import		_ray_setup_py
	.import		_ray_setup_and_cast
	.import		_floor_dli_install
	.import		_floor_dli_set_rotation

.segment	"DATA"

_marker_row:
	.byte	$FF
_nose_row:
	.byte	$FF
_pursuer_row:
	.byte	$FF

.segment	"RODATA"

_dir_dx:
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$01
_dir_dy:
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$FF

.segment	"BSS"

.segment	"HIGHBSS"
.segment	"BSS"
.segment	"SCREEN"
.segment	"BSS"
.segment	"DLIST"
.segment	"BSS"
.segment	"HIGHBSS"
.segment	"BSS"
_col_dist:
	.res	36,$00
.segment	"SCREEN"
_view_buffer:
	.res	3680,$00
.segment	"HIGHBSS"
_height_table:
	.res	400,$00
.segment	"BSS"
_ray_dist:
	.res	2,$00
_ray_height:
	.res	2,$00
_ray_mag:
	.res	2,$00
_ray_top:
	.res	1,$00
_ray_bottom:
	.res	1,$00
_ray_wall:
	.res	1,$00
.segment	"SCREEN"
_hud_line:
	.res	20,$00
.segment	"DLIST"
_view_dlist:
	.res	104,$00
.segment	"HIGHBSS"
_minimap_bits:
	.res	295,$00
.segment	"BSS"
_floor_phase:
	.res	1,$00
_floor_rotation:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ view3d_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_view3d_init: near

	.dbg	func, "view3d_init", "00", static, "_view3d_init"
	.dbg	sym, "addr", "00", auto, -2
	.dbg	sym, "i", "00", auto, -3
	.dbg	sym, "n", "00", auto, -4

.segment	"CODE"

;
; for (i = 0; i < sizeof(hud_line); ++i) hud_line[i] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 433
	jsr     decsp4
	lda     #$00
	ldy     #$01
L0022:	sta     (c_sp),y
	cmp     #$14
	bcs     L0024
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _hud_line,y
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0022
;
; hud_line[16] = HUD_CHAR('B');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 435
L0024:	lda     #$62
	sta     _hud_line+16
;
; hud_line[17] = HUD_DIGIT(BUILD_DIGIT_100);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 436
	lda     #$90
	sta     _hud_line+17
;
; hud_line[18] = HUD_DIGIT(BUILD_DIGIT_10);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 437
	lda     #$92
	sta     _hud_line+18
;
; hud_line[19] = HUD_DIGIT(BUILD_DIGIT_1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 438
	lda     #$96
	sta     _hud_line+19
;
; for (addr = 0; addr < HEIGHT_STEPS; ++addr) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 441
	ldx     #$00
	txa
	iny
	jsr     staxysp
L0007:	ldy     #$03
	lda     (c_sp),y
	cmp     #$01
	bne     L000B
	dey
	lda     (c_sp),y
	cmp     #$90
L000B:	bcs     L0008
;
; n = (addr <= (DIST_MIN >> 4))
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 442
	ldy     #$03
	lda     (c_sp),y
	cmp     #$00
	bne     L000C
	dey
	lda     (c_sp),y
	cmp     #$07
;
; ? VIEW_ROWS
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 443
L000C:	bcs     L000D
;
; : (unsigned char)(WALL_SCALE / (addr << 4) > VIEW_ROWS
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 444
	lda     #$5C
	jmp     L0025
L000D:	ldx     #$5C
	lda     #$00
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     shlax4
	jsr     tosudivax
;
; ? VIEW_ROWS
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 445
	cmp     #$5D
	txa
	sbc     #$00
	bcc     L000F
;
; : WALL_SCALE / (addr << 4));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 446
	lda     #$5C
	jmp     L0025
L000F:	ldx     #$5C
	lda     #$00
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     shlax4
	jsr     tosudivax
L0025:	ldy     #$00
	sta     (c_sp),y
;
; height_table[addr] = n;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 447
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     #<(_height_table)
	sta     ptr1
	txa
	adc     #>(_height_table)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	sta     (ptr1),y
;
; for (addr = 0; addr < HEIGHT_STEPS; ++addr) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 441
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0007
;
; addr = (unsigned int)view_buffer;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 450
L0008:	lda     #<(_view_buffer)
	ldx     #>(_view_buffer)
	ldy     #$02
	jsr     staxysp
;
; n = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 451
	lda     #$00
	tay
	sta     (c_sp),y
;
; view_dlist[n++] = 0x70;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 452
	lda     #$70
	sta     _view_dlist,y
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = 0x70;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 453
	tay
	lda     #$70
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = 0x70;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 454
	tay
	lda     #$70
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = 0x4D;                        /* mode D + load memory scan */
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 455
	tay
	lda     #$4D
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)addr;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 456
	tax
	ldy     #$02
	lda     (c_sp),y
	sta     _view_dlist,x
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)(addr >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 457
	lda     #<(_view_dlist)
	ldx     #>(_view_dlist)
	clc
	adc     (c_sp),y
	bcc     L0016
	inx
L0016:	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; for (i = 1; i < VIEW_ROWS; ++i) view_dlist[n++] = 0x0D;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 458
	lda     #$01
	iny
L0023:	sta     (c_sp),y
	cmp     #$5C
	bcs     L0018
	dey
	lda     (c_sp),y
	tay
	lda     #$0D
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L0023
;
; addr = (unsigned int)hud_line;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 459
L0018:	lda     #<(_hud_line)
	ldx     #>(_hud_line)
	iny
	jsr     staxysp
;
; view_dlist[n++] = 0x46;                        /* mode 6 text + load memory scan */
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 460
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     #$46
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)addr;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 461
	tax
	ldy     #$02
	lda     (c_sp),y
	sta     _view_dlist,x
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)(addr >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 462
	lda     #<(_view_dlist)
	ldx     #>(_view_dlist)
	clc
	adc     (c_sp),y
	bcc     L001E
	inx
L001E:	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; addr = (unsigned int)view_dlist;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 463
	lda     #<(_view_dlist)
	ldx     #>(_view_dlist)
	ldy     #$02
	jsr     staxysp
;
; view_dlist[n++] = 0x41;                        /* jump and wait for vblank */
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 464
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     #$41
	sta     _view_dlist,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)addr;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 465
	tax
	ldy     #$02
	lda     (c_sp),y
	sta     _view_dlist,x
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; view_dlist[n++] = (unsigned char)(addr >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 466
	lda     #<(_view_dlist)
	ldx     #>(_view_dlist)
	clc
	adc     (c_sp),y
	bcc     L0021
	inx
L0021:	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
;
; COLOR0 = COLOR_FLOOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 468
	lda     #$28
	sta     $02C4
;
; COLOR1 = COLOR_WALL_Y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 469
	lda     #$06
	sta     $02C5
;
; COLOR2 = COLOR_WALL_X;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 470
	lda     #$0A
	sta     $02C6
;
; COLOR4 = COLOR_CEILING;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 471
	lda     #$92
	sta     $02C8
;
; OS.sdlst = view_dlist;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 473
	lda     #>(_view_dlist)
	sta     $0230+1
	lda     #<(_view_dlist)
	sta     $0230
;
; OS.sdmctl = 0x22;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 474
	lda     #$22
	sta     $022F
;
; ANTIC.dmactl = 0x22;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 475
	sta     $D400
;
; floor_phase = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 476
	tya
	sta     _floor_phase
;
; floor_rotation = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 477
	sta     _floor_rotation
;
; set_floor_dlis();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 478
	jsr     _set_floor_dlis
;
; floor_dli_install();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 479
	jsr     _floor_dli_install
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 480
	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ view3d_render (unsigned int px, unsigned int py, unsigned int angle)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_view3d_render: near

	.dbg	func, "view3d_render", "00", static, "_view3d_render"
	.dbg	sym, "px", "00", auto, 4
	.dbg	sym, "py", "00", auto, 2
	.dbg	sym, "angle", "00", auto, 0
	.dbg	sym, "col", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 192
	jsr     pushax
;
; for (col = 0; col < VIEW_COLS; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 195
	jsr     decsp1
	lda     #$00
	tay
L0007:	sta     (c_sp),y
	cmp     #$12
	bcs     L0003
;
; cast_column(col, angle + (unsigned int)ray_offset[col], px, py);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 196
	lda     (c_sp),y
	jsr     pusha
	ldx     #$00
	ldy     #$01
	lda     (c_sp),y
	asl     a
	bcc     L0008
	inx
	clc
L0008:	adc     #<(_ray_offset)
	tay
	txa
	adc     #>(_ray_offset)
	tax
	tya
	jsr     ldaxi
	clc
	ldy     #$02
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushax
	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	jsr     _cast_column
;
; for (col = 0; col < VIEW_COLS; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 195
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0007
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 198
L0003:	jmp     incsp7

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ view3d_floor_motion (signed char direction)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_view3d_floor_motion: near

	.dbg	func, "view3d_floor_motion", "00", static, "_view3d_floor_motion"
	.dbg	sym, "direction", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 215
	jsr     pusha
;
; if (direction > 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 216
	ldy     #$00
	lda     (c_sp),y
	sec
	sbc     #$01
	bvs     L0004
	eor     #$80
L0004:	bpl     L000E
;
; if (++floor_phase >= FLOOR_BAND_ROWS) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 217
	inc     _floor_phase
	lda     _floor_phase
	cmp     #$07
	bcc     L000B
;
; floor_phase = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 218
	sty     _floor_phase
;
; floor_rotation = floor_rotation == 0
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 219
	lda     _floor_rotation
;
; ? FLOOR_BANDS - 1 : (unsigned char)(floor_rotation - 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 220
	bne     L000C
	lda     #$05
	jmp     L000D
L000C:	lda     _floor_rotation
	sec
	sbc     #$01
L000D:	sta     _floor_rotation
;
; floor_dli_set_rotation(floor_rotation);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 221
	jsr     _floor_dli_set_rotation
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 223
	jmp     L000B
;
; if (floor_phase == 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 224
L000E:	lda     _floor_phase
	bne     L0010
;
; floor_phase = FLOOR_BAND_ROWS - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 225
	lda     #$06
	sta     _floor_phase
;
; if (++floor_rotation >= FLOOR_BANDS) floor_rotation = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 226
	inc     _floor_rotation
	lda     _floor_rotation
	cmp     #$06
	bcc     L000F
	sty     _floor_rotation
;
; floor_dli_set_rotation(floor_rotation);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 227
L000F:	lda     _floor_rotation
	jsr     _floor_dli_set_rotation
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 228
	jmp     L000B
;
; --floor_phase;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 229
L0010:	dec     _floor_phase
;
; set_floor_dlis();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 232
L000B:	jsr     _set_floor_dlis
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 233
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ view3d_wall_height (unsigned int dist)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_view3d_wall_height: near

	.dbg	func, "view3d_wall_height", "00", static, "_view3d_wall_height"
	.dbg	sym, "dist", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 421
	jsr     pushax
;
; dist >>= 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 422
	jsr     ldax0sp
	jsr     shrax4
	jsr     stax0sp
;
; if (dist >= HEIGHT_STEPS) dist = HEIGHT_STEPS - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 423
	cmp     #$90
	txa
	sbc     #$01
	bcc     L0002
	ldx     #$01
	lda     #$8F
	jsr     stax0sp
;
; return height_table[dist];
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 424
L0002:	jsr     ldax0sp
	sta     ptr1
	txa
	clc
	adc     #>(_height_table)
	sta     ptr1+1
	ldy     #<(_height_table)
	ldx     #$00
	lda     (ptr1),y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 425
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ minimap_build (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_minimap_build: near

	.dbg	func, "minimap_build", "00", static, "_minimap_build"
	.dbg	sym, "row", "00", auto, -1
	.dbg	sym, "col", "00", auto, -2
	.dbg	sym, "byte", "00", auto, -3

.segment	"CODE"

;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 242
	jsr     decsp3
	lda     #$00
	ldy     #$02
L0014:	sta     (c_sp),y
	cmp     #$3B
	jcs     L0003
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 243
	lda     #$00
	tay
L0012:	sta     (c_sp),y
	cmp     #$05
	bcs     L0015
;
; minimap_bits[row][byte] = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 244
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     mulax5
	clc
	adc     #<(_minimap_bits)
	sta     ptr1
	txa
	adc     #>(_minimap_bits)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0010
	inx
L0010:	sta     ptr1
	stx     ptr1+1
	tya
	sta     (ptr1),y
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 243
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0012
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 246
L0015:	tya
	iny
L0013:	sta     (c_sp),y
	cmp     #$14
	bcs     L0004
;
; if (maze_solid(col, row)) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 247
	lda     (c_sp),y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	jsr     _maze_solid
	tax
	beq     L000C
;
; minimap_bits[row][col >> 2] |=
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 248
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     mulax5
	clc
	adc     #<(_minimap_bits)
	sta     ptr1
	txa
	adc     #>(_minimap_bits)
	sta     ptr1+1
	dey
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0011
	inx
;
; (unsigned char)(0x02 << (6 - ((col & 3) << 1)));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 249
L0011:	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	lda     #$02
	jsr     pusha0
	lda     #$06
	jsr     pusha0
	ldy     #$09
	lda     (c_sp),y
	and     #$03
	asl     a
	bcc     L000F
	ldx     #$01
L000F:	jsr     tossubax
	jsr     tosaslax
	jsr     tosora0
	ldy     #$00
	jsr     staspidx
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 246
L000C:	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0013
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 242
L0004:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0014
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 253
L0003:	jmp     incsp3

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ minimap_show (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_minimap_show: near

	.dbg	func, "minimap_show", "00", static, "_minimap_show"
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "row", "00", auto, -3
	.dbg	sym, "byte", "00", auto, -4

.segment	"CODE"

;
; dest = view_buffer;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 262
	jsr     decsp4
	lda     #<(_view_buffer)
	ldx     #>(_view_buffer)
	ldy     #$02
	jsr     staxysp
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 263
	lda     #$00
	ldy     #$01
L000B:	sta     (c_sp),y
	cmp     #$3B
	bcs     L0003
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 264
	lda     #$00
	dey
L000A:	sta     (c_sp),y
	cmp     #$05
	bcs     L0007
;
; dest[byte] = minimap_bits[row][byte];
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 265
	lda     (c_sp),y
	clc
	ldy     #$02
	adc     (c_sp),y
	sta     sreg
	lda     #$00
	iny
	adc     (c_sp),y
	sta     sreg+1
	ldx     #$00
	ldy     #$01
	lda     (c_sp),y
	jsr     mulax5
	clc
	adc     #<(_minimap_bits)
	sta     ptr1
	txa
	adc     #>(_minimap_bits)
	sta     ptr1+1
	dey
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 264
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000A
;
; dest += VIEW_STRIDE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 267
L0007:	ldy     #$02
	ldx     #$00
	lda     #$28
	jsr     addeqysp
;
; for (row = 0; row < MAZE_H; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 263
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L000B
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 269
L0003:	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ minimap_update (unsigned int px, unsigned int py, unsigned int angle, unsigned int pursuer_x, unsigned int pursuer_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_minimap_update: near

	.dbg	func, "minimap_update", "00", static, "_minimap_update"
	.dbg	sym, "px", "00", auto, 8
	.dbg	sym, "py", "00", auto, 6
	.dbg	sym, "angle", "00", auto, 4
	.dbg	sym, "pursuer_x", "00", auto, 2
	.dbg	sym, "pursuer_y", "00", auto, 0
	.dbg	sym, "col", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2
	.dbg	sym, "facing", "00", auto, -3

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 296
	jsr     pushax
;
; minimap_restore_row(marker_row);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 301
	jsr     decsp3
	lda     _marker_row
	jsr     _minimap_restore_row
;
; minimap_restore_row(nose_row);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 302
	lda     _nose_row
	jsr     _minimap_restore_row
;
; minimap_restore_row(pursuer_row);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 303
	lda     _pursuer_row
	jsr     _minimap_restore_row
;
; col = (unsigned char)(px >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 305
	ldy     #$0C
	lda     (c_sp),y
	ldy     #$02
	sta     (c_sp),y
;
; row = (unsigned char)(py >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 306
	ldy     #$0A
	lda     (c_sp),y
	ldy     #$01
	sta     (c_sp),y
;
; facing = (unsigned char)(((((unsigned int)(angle >> 8)) + 16) >> 5) & 7);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 307
	ldy     #$08
	ldx     #$00
	lda     (c_sp),y
	ldy     #$10
	jsr     incaxy
	jsr     shrax4
	jsr     shrax1
	and     #$07
	ldy     #$00
	sta     (c_sp),y
;
; nose_row = (unsigned char)(row + dir_dy[facing]);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 309
	lda     #<(_dir_dy)
	ldx     #>(_dir_dy)
	clc
	adc     (c_sp),y
	bcc     L0006
	inx
L0006:	jsr     ldaidx
	clc
	iny
	adc     (c_sp),y
	sta     _nose_row
;
; minimap_plot((unsigned char)(col + dir_dx[facing]), nose_row, 0x01);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 310
	lda     #<(_dir_dx)
	ldx     #>(_dir_dx)
	clc
	dey
	adc     (c_sp),y
	bcc     L0007
	inx
L0007:	jsr     ldaidx
	clc
	ldy     #$02
	adc     (c_sp),y
	jsr     pusha
	lda     _nose_row
	jsr     pusha
	lda     #$01
	jsr     _minimap_plot
;
; minimap_plot(col, row, 0x03);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 311
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	lda     #$03
	jsr     _minimap_plot
;
; marker_row = row;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 312
	ldy     #$01
	lda     (c_sp),y
	sta     _marker_row
;
; pursuer_row = (unsigned char)(pursuer_y >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 314
	ldy     #$04
	lda     (c_sp),y
	sta     _pursuer_row
;
; minimap_plot((unsigned char)(pursuer_x >> 8), pursuer_row, 0x01);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 315
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	lda     _pursuer_row
	jsr     pusha
	lda     #$01
	jsr     _minimap_plot
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 316
	ldy     #$0D
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ hud_set_fps (unsigned char fps)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hud_set_fps: near

	.dbg	func, "hud_set_fps", "00", static, "_hud_set_fps"
	.dbg	sym, "fps", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 326
	jsr     pusha
;
; if (fps > 99) fps = 99;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 328
	ldy     #$00
	lda     (c_sp),y
	cmp     #$64
	bcc     L0003
	lda     #$63
	sta     (c_sp),y
;
; hud_line[0] = HUD_CHAR('F');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 329
L0003:	lda     #$66
	sta     _hud_line
;
; hud_line[1] = HUD_CHAR('P');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 330
	lda     #$70
	sta     _hud_line+1
;
; hud_line[2] = HUD_CHAR('S');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 331
	lda     #$73
	sta     _hud_line+2
;
; hud_line[4] = HUD_DIGIT(fps / 10);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 332
	lda     (c_sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	ldy     #$10
	jsr     incaxy
	ora     #$80
	sta     _hud_line+4
;
; hud_line[5] = HUD_DIGIT(fps % 10);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 333
	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	ldy     #$10
	jsr     incaxy
	ora     #$80
	sta     _hud_line+5
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 337
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ hud_set_targets (unsigned char remaining)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hud_set_targets: near

	.dbg	func, "hud_set_targets", "00", static, "_hud_set_targets"
	.dbg	sym, "remaining", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 340
	jsr     pusha
;
; if (remaining > 99) remaining = 99;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 342
	ldy     #$00
	lda     (c_sp),y
	cmp     #$64
	bcc     L0003
	lda     #$63
	sta     (c_sp),y
;
; hud_line[10] = HUD_CHAR('T');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 343
L0003:	lda     #$74
	sta     _hud_line+10
;
; hud_line[11] = HUD_CHAR('G');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 344
	lda     #$67
	sta     _hud_line+11
;
; hud_line[12] = HUD_CHAR('T');
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 345
	lda     #$74
	sta     _hud_line+12
;
; hud_line[14] = HUD_DIGIT(remaining / 10);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 346
	lda     (c_sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	ldy     #$10
	jsr     incaxy
	ora     #$80
	sta     _hud_line+14
;
; hud_line[15] = HUD_DIGIT(remaining % 10);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 347
	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	ldy     #$10
	jsr     incaxy
	ora     #$80
	sta     _hud_line+15
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 351
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ hud_set_game (unsigned char lives, unsigned char level, unsigned int score, unsigned int high_score)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hud_set_game: near

	.dbg	func, "hud_set_game", "00", static, "_hud_set_game"
	.dbg	sym, "lives", "00", auto, 5
	.dbg	sym, "level", "00", auto, 4
	.dbg	sym, "score", "00", auto, 2
	.dbg	sym, "high_score", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 369
	jsr     pushax
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 391
	jmp     incsp6

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ hud_set_decoy (unsigned char progress, unsigned char maximum)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hud_set_decoy: near

	.dbg	func, "hud_set_decoy", "00", static, "_hud_set_decoy"
	.dbg	sym, "progress", "00", auto, 1
	.dbg	sym, "maximum", "00", auto, 0
	.dbg	sym, "filled", "00", auto, -1
	.dbg	sym, "col", "00", auto, -2
	.dbg	sym, "row", "00", auto, -3
	.dbg	sym, "value", "00", auto, -4
	.dbg	sym, "shift", "00", auto, -5
	.dbg	sym, "dest", "00", auto, -7

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 394
	jsr     pusha
;
; filled = maximum == 0 ? DECOY_BAR_INNER_WIDTH
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 402
	jsr     decsp7
	ldy     #$07
	lda     (c_sp),y
	bne     L0002
;
; : (unsigned char)(((unsigned int)progress * DECOY_BAR_INNER_WIDTH) / maximum);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 403
	lda     #$12
	jmp     L0018
L0002:	iny
	lda     (c_sp),y
	jsr     pusha0
	lda     #$12
	jsr     tosumula0
	jsr     pushax
	ldy     #$09
	lda     (c_sp),y
	jsr     tosudiva0
L0018:	ldy     #$06
	sta     (c_sp),y
;
; if (filled > DECOY_BAR_INNER_WIDTH) filled = DECOY_BAR_INNER_WIDTH;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 404
	cmp     #$13
	lda     #$00
	bcc     L001A
	lda     #$12
	sta     (c_sp),y
;
; for (row = 0; row < DECOY_BAR_HEIGHT; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 406
	lda     #$00
L001A:	ldy     #$04
L0016:	sta     (c_sp),y
	cmp     #$06
	jcs     L0006
;
; dest = view_buffer + (unsigned int)(DECOY_BAR_TOP + row) * VIEW_STRIDE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 407
	ldx     #$00
	lda     (c_sp),y
	ldy     #$3D
	jsr     incaxy
	jsr     pushax
	lda     #$28
	jsr     tosumula0
	clc
	adc     #<(_view_buffer)
	tay
	txa
	adc     #>(_view_buffer)
	tax
	tya
	jsr     stax0sp
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 408
	lda     #$00
	ldy     #$05
L0015:	sta     (c_sp),y
	cmp     #$14
	jcs     L0007
;
; if (row == 0 || row == DECOY_BAR_HEIGHT - 1 || col == 0 || col == MAZE_W - 1)
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 409
	dey
	lda     (c_sp),y
	beq     L001B
	cmp     #$05
	beq     L001B
	iny
	lda     (c_sp),y
	beq     L001B
	cmp     #$13
	bne     L001D
;
; value = 2;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 410
L001B:	lda     #$02
;
; else
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 411
	jmp     L0020
;
; value = col <= filled ? 3 : 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 412
L001D:	lda     (c_sp),y
	iny
	cmp     (c_sp),y
	beq     L001E
	bcs     L001F
L001E:	lda     #$03
	jmp     L0020
L001F:	lda     #$00
L0020:	ldy     #$03
	sta     (c_sp),y
;
; shift = (unsigned char)(6 - ((col & 3) << 1));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 413
	lda     #$06
	jsr     pusha0
	ldy     #$07
	lda     (c_sp),y
	and     #$03
	asl     a
	bcc     L0013
	ldx     #$01
L0013:	jsr     tossubax
	ldy     #$02
	sta     (c_sp),y
;
; dest[col >> 2] = (unsigned char)(
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 414
	ldx     #$00
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr2
	txa
	iny
	adc     (c_sp),y
	sta     ptr2+1
;
; (dest[col >> 2] & ~(0x03 << shift)) | (value << shift));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 415
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	ldy     #$00
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     (ptr1,x)
	sta     ptr1
	iny
	lda     (c_sp),y
	tay
	lda     #$03
	jsr     aslaxy
	eor     #$FF
	and     ptr1
	sta     sreg
	ldx     #$00
	ldy     #$03
	lda     (c_sp),y
	sta     ptr1
	dey
	lda     (c_sp),y
	tay
	lda     ptr1
	jsr     aslaxy
	ora     sreg
	ldy     #$00
	sta     (ptr2),y
;
; for (col = 0; col < MAZE_W; ++col) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 408
	ldy     #$05
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0015
;
; for (row = 0; row < DECOY_BAR_HEIGHT; ++row) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 406
L0007:	dey
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0016
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 418
L0006:	ldy     #$09
	jmp     addysp

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ draw_open_byte (unsigned char x)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_open_byte: near

	.dbg	func, "draw_open_byte", "00", static, "_draw_open_byte"
	.dbg	sym, "x", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 101
	jsr     pusha
;
; col3d_x = x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 102
	ldy     #$00
	lda     (c_sp),y
	sta     _col3d_x
;
; col3d_row = HORIZON;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 103
	lda     #$2E
	sta     _col3d_row
;
; col3d_color = PIX_FLOOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 104
	lda     #$55
	sta     _col3d_color
;
; col3d_fill_down();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 105
	jsr     _col3d_fill_down
;
; col3d_row = HORIZON - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 106
	lda     #$2D
	sta     _col3d_row
;
; col3d_color = PIX_CEILING;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 107
	lda     #$00
	sta     _col3d_color
;
; col3d_fill_up();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 108
	jsr     _col3d_fill_up
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 109
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ draw_open_column (unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_open_column: near

	.dbg	func, "draw_open_column", "00", static, "_draw_open_column"
	.dbg	sym, "col", "00", auto, 0
	.dbg	sym, "x", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 112
	jsr     pusha
;
; x = (unsigned char)(MINI_BYTES + (col << 1));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 115
	jsr     decsp1
	ldy     #$01
	lda     (c_sp),y
	asl     a
	clc
	adc     #$05
	dey
	sta     (c_sp),y
;
; draw_open_byte(x);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 116
	jsr     _draw_open_byte
;
; if (x + 1 < VIEW_STRIDE) draw_open_byte(x + 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 117
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	cmp     #$28
	txa
	sbc     #$00
	bvc     L0003
	eor     #$80
L0003:	bpl     L0002
	lda     (c_sp),y
	clc
	adc     #$01
	jsr     _draw_open_byte
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 118
L0002:	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ draw_wall_byte (unsigned char x, unsigned char top, unsigned char bottom, unsigned char wall)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_wall_byte: near

	.dbg	func, "draw_wall_byte", "00", static, "_draw_wall_byte"
	.dbg	sym, "x", "00", auto, 3
	.dbg	sym, "top", "00", auto, 2
	.dbg	sym, "bottom", "00", auto, 1
	.dbg	sym, "wall", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 122
	jsr     pusha
;
; col3d_x = x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 123
	ldy     #$03
	lda     (c_sp),y
	sta     _col3d_x
;
; col3d_row = top;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 124
	dey
	lda     (c_sp),y
	sta     _col3d_row
;
; col3d_end = bottom + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 125
	dey
	lda     (c_sp),y
	clc
	adc     #$01
	sta     _col3d_end
;
; col3d_color = wall;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 126
	dey
	lda     (c_sp),y
	sta     _col3d_color
;
; col3d_fill_span();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 127
	jsr     _col3d_fill_span
;
; if (bottom < VIEW_ROWS - 1) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 128
	ldy     #$01
	lda     (c_sp),y
	cmp     #$5B
	bcs     L0002
;
; col3d_row = bottom + 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 129
	clc
	adc     #$01
	sta     _col3d_row
;
; col3d_color = PIX_FLOOR;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 130
	lda     #$55
	sta     _col3d_color
;
; col3d_fill_down();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 131
	jsr     _col3d_fill_down
;
; if (top > 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 133
L0002:	ldy     #$02
	lda     (c_sp),y
	beq     L0003
;
; col3d_row = top - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 134
	sec
	sbc     #$01
	sta     _col3d_row
;
; col3d_color = PIX_CEILING;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 135
	lda     #$00
	sta     _col3d_color
;
; col3d_fill_up();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 136
	jsr     _col3d_fill_up
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 138
L0003:	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ draw_wall_column (unsigned char col, unsigned char top, unsigned char bottom, unsigned char wall)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_wall_column: near

	.dbg	func, "draw_wall_column", "00", static, "_draw_wall_column"
	.dbg	sym, "col", "00", auto, 3
	.dbg	sym, "top", "00", auto, 2
	.dbg	sym, "bottom", "00", auto, 1
	.dbg	sym, "wall", "00", auto, 0
	.dbg	sym, "x", "00", auto, -1

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 142
	jsr     pusha
;
; x = (unsigned char)(MINI_BYTES + (col << 1));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 145
	jsr     decsp1
	ldy     #$04
	lda     (c_sp),y
	asl     a
	clc
	adc     #$05
	ldy     #$00
	sta     (c_sp),y
;
; draw_wall_byte(x, top, bottom, wall);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 146
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     _draw_wall_byte
;
; if (x + 1 < VIEW_STRIDE) draw_wall_byte(x + 1, top, bottom, wall);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 147
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	cmp     #$28
	txa
	sbc     #$00
	bvc     L0003
	eor     #$80
L0003:	bpl     L0002
	lda     (c_sp),y
	clc
	adc     #$01
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     _draw_wall_byte
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 148
L0002:	jmp     incsp5

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ cast_column (unsigned char col, unsigned int ray_angle, unsigned int px, unsigned int py)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cast_column: near

	.dbg	func, "cast_column", "00", static, "_cast_column"
	.dbg	sym, "col", "00", auto, 6
	.dbg	sym, "ray_angle", "00", auto, 4
	.dbg	sym, "px", "00", auto, 2
	.dbg	sym, "py", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 152
	jsr     pushax
;
; ray_setup_angle = ray_angle;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 153
	ldy     #$05
	jsr     ldaxysp
	sta     _ray_setup_angle
	stx     _ray_setup_angle+1
;
; ray_setup_px = px;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 154
	ldy     #$03
	jsr     ldaxysp
	sta     _ray_setup_px
	stx     _ray_setup_px+1
;
; ray_setup_py = py;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 155
	jsr     ldax0sp
	sta     _ray_setup_py
	stx     _ray_setup_py+1
;
; ray_setup_and_cast();
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 156
	jsr     _ray_setup_and_cast
;
; if (!dda_hit) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 158
	lda     _dda_hit
	bne     L0002
;
; col_dist[col] = 0xFFFFu;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 159
	ldy     #$06
	tax
	lda     (c_sp),y
	asl     a
	bcc     L000D
	inx
	clc
L000D:	adc     #<(_col_dist)
	sta     ptr1
	txa
	adc     #>(_col_dist)
	sta     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; draw_open_column(col);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 160
	ldy     #$06
	lda     (c_sp),y
	jsr     _draw_open_column
;
; return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 161
	jmp     incsp7
;
; if (dda_side == 0) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 164
L0002:	lda     _dda_side
	bne     L0003
;
; ray_dist = dda_side_x - dda_delta_x;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 165
	lda     _dda_side_x
	sec
	sbc     _dda_delta_x
	sta     _ray_dist
	lda     _dda_side_x+1
	sbc     _dda_delta_x+1
	sta     _ray_dist+1
;
; ray_wall = PIX_WALL_X;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 166
	lda     #$FF
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 167
	jmp     L000B
;
; ray_dist = dda_side_y - dda_delta_y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 168
L0003:	lda     _dda_side_y
	sec
	sbc     _dda_delta_y
	sta     _ray_dist
	lda     _dda_side_y+1
	sbc     _dda_delta_y+1
	sta     _ray_dist+1
;
; ray_wall = PIX_WALL_Y;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 169
	lda     #$AA
L000B:	sta     _ray_wall
;
; ray_mag = cos_rel[col];
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 172
	ldy     #$06
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L000E
	inx
	clc
L000E:	adc     #<(_cos_rel)
	tay
	txa
	adc     #>(_cos_rel)
	tax
	tya
	jsr     ldaxi
	sta     _ray_mag
	stx     _ray_mag+1
;
; ray_dist = ((ray_dist >> 8) * ray_mag)
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 173
	lda     _ray_dist+1
	jsr     pusha0
	lda     _ray_mag
	ldx     _ray_mag+1
	jsr     tosumulax
;
; + (((ray_dist & 0x00FFu) * ray_mag) >> 8);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 174
	jsr     pushax
	lda     _ray_dist
	jsr     pusha0
	lda     _ray_mag
	ldx     _ray_mag+1
	jsr     tosumulax
	txa
	jsr     tosadda0
	sta     _ray_dist
	stx     _ray_dist+1
;
; col_dist[col] = ray_dist;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 175
	ldy     #$06
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L000F
	inx
	clc
L000F:	adc     #<(_col_dist)
	sta     ptr1
	txa
	adc     #>(_col_dist)
	sta     ptr1+1
	lda     _ray_dist
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     _ray_dist+1
	sta     (ptr1),y
;
; ray_dist >>= 4;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 177
	lda     _ray_dist
	ldx     _ray_dist+1
	jsr     shrax4
	sta     _ray_dist
	stx     _ray_dist+1
;
; if (ray_dist >= HEIGHT_STEPS) ray_dist = HEIGHT_STEPS - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 178
	cmp     #$90
	txa
	sbc     #$01
	bcc     L0005
	ldx     #$01
	lda     #$8F
	sta     _ray_dist
	stx     _ray_dist+1
;
; ray_height = height_table[ray_dist];
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 179
L0005:	lda     _ray_dist
	sta     ptr1
	lda     _ray_dist+1
	clc
	adc     #>(_height_table)
	sta     ptr1+1
	ldy     #<(_height_table)
	ldx     #$00
	lda     (ptr1),y
	sta     _ray_height
	stx     _ray_height+1
;
; if (ray_height >= VIEW_ROWS) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 181
	cmp     #$5C
	txa
	sbc     #$00
	bcc     L0010
;
; ray_top = 0;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 182
	stx     _ray_top
;
; ray_bottom = VIEW_ROWS - 1;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 183
	lda     #$5B
;
; } else {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 184
	jmp     L000C
;
; ray_top = (unsigned char)((VIEW_ROWS - ray_height) >> 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 185
L0010:	lda     #$5C
	sec
	sbc     _ray_height
	pha
	txa
	sbc     _ray_height+1
	tax
	pla
	jsr     shrax1
	sta     _ray_top
;
; ray_bottom = (unsigned char)(ray_top + ray_height - 1);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 186
	clc
	adc     _ray_height
	sec
	sbc     #$01
L000C:	sta     _ray_bottom
;
; draw_wall_column(col, ray_top, ray_bottom, ray_wall);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 188
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	lda     _ray_top
	jsr     pusha
	lda     _ray_bottom
	jsr     pusha
	lda     _ray_wall
	jsr     _draw_wall_column
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 189
	jmp     incsp7

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ set_floor_dlis (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_floor_dlis: near

	.dbg	func, "set_floor_dlis", "00", static, "_set_floor_dlis"
	.dbg	sym, "i", "00", auto, -1
	.dbg	sym, "row", "00", auto, -2

.segment	"CODE"

;
; for (row = HORIZON - 1; row < VIEW_ROWS; ++row)
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 205
	jsr     decsp2
	lda     #$2D
	ldy     #$00
L000A:	sta     (c_sp),y
	cmp     #$5C
	bcs     L000C
;
; view_dlist[5 + row] &= 0x7F;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 206
	ldx     #$00
	lda     (c_sp),y
	jsr     incax5
	clc
	adc     #<(_view_dlist)
	sta     ptr1
	txa
	adc     #>(_view_dlist)
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	and     #$7F
	sta     (ptr1),y
;
; for (row = HORIZON - 1; row < VIEW_ROWS; ++row)
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 205
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000A
;
; for (i = 0; i < FLOOR_BANDS; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 207
L000C:	tya
	iny
L000B:	sta     (c_sp),y
	cmp     #$06
	bcs     L000D
;
; row = (unsigned char)(HORIZON + floor_phase + i * FLOOR_BAND_ROWS);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 208
	ldx     #$00
	lda     _floor_phase
	ldy     #$2E
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	ldx     #$00
	ldy     #$01
	lda     (c_sp),y
	jsr     mulax7
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	pla
	dey
	sta     (c_sp),y
;
; view_dlist[5 + row - 1] |= 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 209
	ldx     #$00
	lda     (c_sp),y
	jsr     incax4
	clc
	adc     #<(_view_dlist)
	sta     ptr1
	txa
	adc     #>(_view_dlist)
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ora     #$80
	sta     (ptr1),y
;
; for (i = 0; i < FLOOR_BANDS; ++i) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 207
	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L000B
;
; view_dlist[5 + VIEW_ROWS - 1] |= 0x80;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 211
L000D:	lda     _view_dlist+96
	ora     #$80
	sta     _view_dlist+96
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 212
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ minimap_restore_row (unsigned char row)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_minimap_restore_row: near

	.dbg	func, "minimap_restore_row", "00", static, "_minimap_restore_row"
	.dbg	sym, "row", "00", auto, 0
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "byte", "00", auto, -3

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 272
	jsr     pusha
;
; if (row >= MAZE_H) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 276
	jsr     decsp3
	ldy     #$03
	lda     (c_sp),y
	cmp     #$3B
	bcs     L0004
;
; dest = view_buffer + (unsigned int)row * VIEW_STRIDE;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 277
	lda     (c_sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	clc
	adc     #<(_view_buffer)
	tay
	txa
	adc     #>(_view_buffer)
	tax
	tya
	ldy     #$01
	jsr     staxysp
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 278
	lda     #$00
	tay
L0007:	sta     (c_sp),y
	cmp     #$05
	bcs     L0004
;
; dest[byte] = minimap_bits[row][byte];
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 279
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	sta     sreg
	lda     #$00
	iny
	adc     (c_sp),y
	sta     sreg+1
	ldx     #$00
	iny
	lda     (c_sp),y
	jsr     mulax5
	clc
	adc     #<(_minimap_bits)
	sta     ptr1
	txa
	adc     #>(_minimap_bits)
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
;
; for (byte = 0; byte < MINI_BYTES; ++byte) {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 278
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0007
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 281
L0004:	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ minimap_plot (unsigned char col, unsigned char row, unsigned char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_minimap_plot: near

	.dbg	func, "minimap_plot", "00", static, "_minimap_plot"
	.dbg	sym, "col", "00", auto, 2
	.dbg	sym, "row", "00", auto, 1
	.dbg	sym, "value", "00", auto, 0
	.dbg	sym, "dest", "00", auto, -2
	.dbg	sym, "shift", "00", auto, -3

.segment	"CODE"

;
; {
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 284
	jsr     pusha
;
; if (col >= MAZE_W || row >= MAZE_H) return;
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 288
	jsr     decsp3
	ldy     #$05
	lda     (c_sp),y
	cmp     #$14
	bcs     L0001
	dey
	lda     (c_sp),y
	cmp     #$3B
	bcs     L0001
;
; shift = (unsigned char)(6 - ((col & 3) << 1));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 289
	lda     #$06
	jsr     pusha0
	ldy     #$07
	lda     (c_sp),y
	and     #$03
	asl     a
	bcc     L0005
	ldx     #$01
L0005:	jsr     tossubax
	ldy     #$00
	sta     (c_sp),y
;
; dest = view_buffer + (unsigned int)row * VIEW_STRIDE + (col >> 2);
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 290
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	clc
	adc     #<(_view_buffer)
	sta     ptr1
	txa
	adc     #>(_view_buffer)
	sta     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0006
	inx
L0006:	ldy     #$01
	jsr     staxysp
;
; *dest = (unsigned char)((*dest & ~(0x03 << shift)) | (value << shift));
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 291
	sta     ptr2
	stx     ptr2+1
	ldy     #$02
	jsr     ldptr1ysp
	ldy     #$00
	lda     (ptr1),y
	sta     ptr1
	lda     (c_sp),y
	tay
	lda     #$03
	ldx     #$00
	jsr     aslaxy
	eor     #$FF
	and     ptr1
	sta     sreg
	ldx     #$00
	ldy     #$03
	lda     (c_sp),y
	sta     ptr1
	lda     (c_sp,x)
	tay
	lda     ptr1
	jsr     aslaxy
	ora     sreg
	ldy     #$00
	sta     (ptr2),y
;
; }
;
	.dbg	line, "C:\Users\Alex\Chased3D\view3d.c", 292
L0001:	jmp     incsp6

	.dbg	line
.endproc

