"""Generates trig3d.c / trig3d.h: fixed-point tables for the Chased3D raycaster.

All tables use 8.8 fixed point (256 == 1.0). Angles use a 256-step circle so
that an 8-bit index wraps naturally.
"""

import math

VIEW_COLS = 18
FOV_DEGREES = 60.0
RECIP_CLAMP = 0x3FFF


def rows(values, per_line, formatter):
    out = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        out.append("    " + " ".join(formatter(v) for v in chunk))
    return "\n".join(out)


def main():
    sin_table = [round(256.0 * math.sin(2.0 * math.pi * i / 256.0)) for i in range(256)]

    # recip[m] == 65536 / m in 8.8, clamped so DDA accumulators cannot overflow.
    recip = [RECIP_CLAMP]
    for m in range(1, 257):
        recip.append(min(RECIP_CLAMP, 65536 // m))

    ray_offset = []
    cos_rel = []
    for col in range(VIEW_COLS):
        rel_deg = (col + 0.5 - VIEW_COLS / 2.0) * (FOV_DEGREES / VIEW_COLS)
        ray_offset.append(round(rel_deg / 360.0 * 65536.0))
        cos_rel.append(round(256.0 * math.cos(math.radians(rel_deg))))

    header = f"""/* Generated by gen_trig3d.py - do not edit by hand. */
#ifndef TRIG3D_H
#define TRIG3D_H

#define TRIG3D_VIEW_COLS {VIEW_COLS}
#define TRIG3D_ONE 256

extern const int sin3d[256];
extern const unsigned int recip3d[257];
extern const int ray_offset[TRIG3D_VIEW_COLS];
extern const unsigned int cos_rel[TRIG3D_VIEW_COLS];

#endif
"""

    source = f"""/* Generated by gen_trig3d.py - do not edit by hand. */
#include "trig3d.h"

const int sin3d[256] = {{
{rows(sin_table, 8, lambda v: f"{v}," )}
}};

const unsigned int recip3d[257] = {{
{rows(recip, 8, lambda v: f"{v}u," )}
}};

const int ray_offset[TRIG3D_VIEW_COLS] = {{
{rows(ray_offset, 8, lambda v: f"{v}," )}
}};

const unsigned int cos_rel[TRIG3D_VIEW_COLS] = {{
{rows(cos_rel, 8, lambda v: f"{v}u," )}
}};
"""

    with open("trig3d.h", "w", encoding="ascii") as handle:
        handle.write(header)
    with open("trig3d.c", "w", encoding="ascii") as handle:
        handle.write(source)

    print(f"sin3d range: {min(sin_table)}..{max(sin_table)}")
    print(f"recip3d[1]={recip[1]} recip3d[256]={recip[256]}")
    print(f"ray_offset range: {min(ray_offset)}..{max(ray_offset)}")
    print(f"cos_rel range: {min(cos_rel)}..{max(cos_rel)}")


if __name__ == "__main__":
    main()
