/* Generated by gen_trig3d.py - do not edit by hand. */
#ifndef TRIG3D_H
#define TRIG3D_H

#define TRIG3D_VIEW_COLS 18
#define TRIG3D_ONE 256

extern const int sin3d[256];
extern const unsigned int recip3d[257];
extern const int ray_offset[TRIG3D_VIEW_COLS];
extern const unsigned int cos_rel[TRIG3D_VIEW_COLS];

#endif
